kube-logging/logging-operator

cmd/logging-operator/fluentd/fluentd.go
pkg/stub/handler.go

Add mutex to app config

---

README.md

| Bug fix?        | yes|
| New feature?    | no|
| Deprecations?   | no|
| Related tickets | fixes #60 
Fix missing label from example in Readme

Fix glich on Readme

---

README.md

README.md License Update

---

developer.md

Initial developer guide

---

cmd/docgen/docgen.go
docs/plugins/alibaba.md
docs/plugins/azure.md
docs/plugins/gcs.md
docs/plugins/parser.md
docs/plugins/s3.md
pkg/resources/plugins/alibaba.go
pkg/resources/plugins/azure.go
pkg/resources/plugins/gcs.go
pkg/resources/plugins/init.go
pkg/resources/plugins/s3.go

This is the first PoC version of an automated markdown document generator. We will evaluate the possibilities to use this as custom resource documentation with description and examples.

Document generator for supported plugins

---

pkg/k8sutil/resource.go

| Bug fix?        |yes|
| New feature?    | no|
| Deprecations?   | no|
| Related tickets | fixes #68 
Handle persistent volume claim update.
#69

Handle Persistent Volume Claim update

---

README.md

Docker pulls badge

---

.circleci/config.yml
Makefile
hack/minio-mc.yaml
hack/minio.yaml
hack/test-s3-output.yaml
hack/test.sh
pkg/resources/plugins/s3.go
scripts/fmt-check.sh
scripts/misspell-check.sh

| Related tickets |  #4 
This PR extends circleci config with basic end-to-end test using minikube as kubernetes cluster, and minio as s3 backend.

Basic e2e test

---

pkg/controller/plugin/plugin_controller.go
pkg/resources/plugins/configmap.go
pkg/resources/plugins/init.go

Namespace fix

---

README.md
docs/plugins/s3.md
pkg/resources/plugins/s3.go

| Related tickets | fixes #89 

S3 plugin auth

---

hack/test.sh
pkg/resources/fluentd/fluentd.go
pkg/resources/fluentd/rbac.go
pkg/resources/templates/templates.go

| Related tickets | fixes #85 

Add fluentd rbac

---

docs/plugins/elasticsearch.md
docs/plugins/parser.md
pkg/resources/plugins/elasticsearch.go
pkg/resources/plugins/parser.go

| Related tickets | fixes #112 #113
Additional configuration flags for es and parser plugins, see #112, #113

extend parser and es plugins to include fields requested in #112 #113

---

Gopkg.lock
charts/logging-operator-fluent/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
charts/nginx-logging-demo/Chart.yaml

| Related tickets | fixes #112 , #113 , #110 #111 
New fields for the elasticsearch plugin and support for the out_forward plugin to forward logs to remote fluentd deployments

bump versions for release, fix Gopkg.lock

---

api/v1alpha2/fluentbit_types.go
charts/logging-operator/templates/logging.banzaicloud.com_clusterflows.yaml
charts/logging-operator/templates/logging.banzaicloud.com_clusteroutputs.yaml
charts/logging-operator/templates/logging.banzaicloud.com_flows.yaml
charts/logging-operator/templates/logging.banzaicloud.com_loggings.yaml
charts/logging-operator/templates/logging.banzaicloud.com_outputs.yaml
config/crd/bases/logging.banzaicloud.com_clusterflows.yaml
config/crd/bases/logging.banzaicloud.com_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.com_flows.yaml
config/crd/bases/logging.banzaicloud.com_loggings.yaml
docs/crds.md
docs/examples/logging_flow_with_filters.yaml
pkg/resources/fluentbit/config.go
pkg/resources/fluentbit/configsecret.go

Add optional parser configuration to support cri format

---

cmd/docs.go
config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_outputs.yaml
docs/developers.md
docs/plugins/outputs/azurestore.md
docs/plugins/outputs/elasticsearch.md
docs/plugins/outputs/loki.md
docs/plugins/outputs/oss.md
docs/plugins/outputs/sumologic.md
pkg/model/filter/tagnormaliser.go
pkg/model/output/azurestore.go
pkg/model/output/elasticsearch.go
pkg/model/output/loki.go
pkg/model/output/oss.go
pkg/model/output/s3.go
pkg/model/output/sumologic.go

Output plugin documentation complement

---

charts/logging-operator-fluent/Chart.yaml
charts/logging-operator-fluent/README.md
charts/logging-operator-fluent/templates/fluentbit-cr.yaml
charts/logging-operator-fluent/templates/fluentd-cr.yaml
charts/logging-operator-fluent/values.yaml

Fluentd and Fluentbit container resources exposed

---

config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_outputs.yaml
docs/plugins/outputs/elasticsearch.md
go.mod
go.sum
pkg/model/output/elasticsearch.go

Elasticsearch type_name fix

---

.circleci/config.yml

Docker build

---

.idea/copyright/profiles_settings.xml
charts/nginx-logging-loki-demo/Chart.yaml
charts/nginx-logging-loki-demo/templates/logging_output.yaml
cmd/docs.go
config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_outputs.yaml
docs/example-loki-nginx.md
docs/plugins/outputs/loki.md
go.mod
go.sum
pkg/model/output/loki.go
pkg/model/output/loki_test.go
pkg/model/output/zz_generated.deepcopy.go
pkg/model/render/test_helper.go
pkg/model/types/stringmaps.go
pkg/util/util.go

| Related tickets | #178 
As Loki changed push format and we plans to switch to the official output plugin this PR will allow to use it.

Loki update

---

config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_outputs.yaml
docs/plugins/outputs/buffer.md
pkg/model/filter/dedot.go
pkg/model/filter/geoip.go
pkg/model/filter/parser.go
pkg/model/filter/record_transformer.go
pkg/model/filter/stdout.go
pkg/model/filter/tagnormaliser.go
pkg/model/input/forward.go
pkg/model/input/tail.go
pkg/model/output/azurestore.go
pkg/model/output/buffer.go
pkg/model/output/elasticsearch.go
pkg/model/output/file.go
pkg/model/output/forward.go
pkg/model/output/gcs.go
pkg/model/output/kafka.go
pkg/model/output/loki.go
pkg/model/output/loki_test.go
pkg/model/output/null.go
pkg/model/output/oss.go
pkg/model/output/s3.go
pkg/model/output/sumologic.go
pkg/model/render/fluent_test.go
pkg/model/render/json_test.go
pkg/model/render/test_helper.go
pkg/model/types/router.go
pkg/resources/model/system.go

| Related tickets | fixes #191 

Fix plugin IDs and Buffer path default

---

config/crd/bases/logging.banzaicloud.io_clusterflows.yaml
config/crd/bases/logging.banzaicloud.io_flows.yaml
docs/plugins/filters/parser.md
pkg/model/filter/parser.go

| Related tickets | fixes #192 

Add missing options to Parser

---

charts/logging-operator/Chart.yaml
charts/logging-operator/templates/logging.banzaicloud.io_clusterflows.yaml
charts/logging-operator/templates/logging.banzaicloud.io_clusteroutputs.yaml
charts/logging-operator/templates/logging.banzaicloud.io_flows.yaml
charts/logging-operator/templates/logging.banzaicloud.io_loggings.yaml
charts/logging-operator/templates/logging.banzaicloud.io_outputs.yaml

Update CRDs in Helm chart.
Apparently the CRDs were not updated when updating the Helm chart.

Update CRDs in Helm chart

---

pkg/model/output/azurestore_test.go
pkg/model/output/elasticsearch_test.go
pkg/model/output/gcs_test.go
pkg/model/output/kafka_test.go
pkg/model/output/oss_test.go
pkg/model/output/s3_test.go
pkg/model/output/sumologic_test.go

Fluentd output tests

---

charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/templates/logging.banzaicloud.io_clusteroutputs.yaml
charts/logging-operator/templates/logging.banzaicloud.io_loggings.yaml
charts/logging-operator/templates/logging.banzaicloud.io_outputs.yaml
charts/logging-operator/values.yaml
charts/nginx-logging-cw-demo/Chart.yaml
charts/nginx-logging-demo/Chart.yaml
charts/nginx-logging-es-demo/Chart.yaml
charts/nginx-logging-kafka-demo/Chart.yaml
charts/nginx-logging-loki-demo/Chart.yaml

Release 2.4.0

---

pkg/sdk/model/output/buffer.go
pkg/sdk/model/output/format.go

| Related tickets | fixes #X, partially #Y, mentioned in #Z

fix reference issues

---

charts/logging-operator-logging/README.md
charts/logging-operator/README.md
docs/crds.md
pkg/sdk/api/v1beta1/logging_types.go

FluentD image for Kinesis support
| New feature?    |yes
| Related tickets | #220 

Kinesis output support

---

charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/templates/logging.banzaicloud.io_loggings.yaml
charts/logging-operator/values.yaml
charts/nginx-logging-cw-demo/Chart.yaml
charts/nginx-logging-demo/Chart.yaml
charts/nginx-logging-es-demo/Chart.yaml
charts/nginx-logging-kafka-demo/Chart.yaml
charts/nginx-logging-loki-demo/Chart.yaml

Bump versions and update CRDs for the release

Release 2.5.0

---

controllers/logging_controller.go
main.go
pkg/resources/fluentbit/configsecret.go
pkg/resources/fluentbit/daemonset.go
pkg/resources/fluentbit/fluentbit.go
pkg/sdk/api/v1beta1/fluentbit_types.go

| Related tickets | fixes #221 

Detect cri for Fluentbit default parser

---

charts/nginx-logging-cw-demo/templates/logging_flow.yaml
charts/nginx-logging-demo/templates/logging_flow.yaml
charts/nginx-logging-es-demo/templates/logging_flow.yaml
charts/nginx-logging-kafka-demo/templates/logging_flow.yaml
charts/nginx-logging-loki-demo/templates/logging_flow.yaml
config/crd/bases/logging.banzaicloud.io_clusterflows.yaml
config/crd/bases/logging.banzaicloud.io_flows.yaml
docs/crds.md
docs/example-cloudwatch-nginx.md
docs/example-es-nginx.md
docs/example-kafka-nginx.md
docs/example-loki-nginx.md
docs/examples/logging_flow_geoip.yaml
docs/examples/logging_flow_with_dedot.yaml
docs/examples/logging_flow_with_filters.yaml
docs/logging-operator-monitoring.md
docs/plugins/filters/concat.md
docs/plugins/filters/geoip.md
docs/plugins/filters/parser.md
main.go
pkg/sdk/model/filter/concat.go
pkg/sdk/model/filter/geoip.go
pkg/sdk/model/filter/parser.go
pkg/sdk/model/types/types.go

| Related tickets | fixes #232 
This PR provide a way to get the actual name of the field with logging content.

CRI based defaults to get record field name for log

---

fluentd-image/v1.7/Dockerfile
fluentd-image/v1.7/entrypoint.sh
fluentd-image/v1.7/fluent.conf

| Related tickets | fixes #237 

new fluentd Image

---

pkg/resources/model/system.go

Fix parser

---

Makefile
charts/logging-operator/templates/logging.banzaicloud.io_clusterflows.yaml
charts/logging-operator/templates/logging.banzaicloud.io_flows.yaml
charts/logging-operator/templates/logging.banzaicloud.io_loggings.yaml

Add crd copy to manifests makefile target, and add to diff-check to avoid forgetting to commit. Also add go mod tidy to the check.

Manifest update check + go mod tidy

---

charts/logging-operator-logging/values.yaml
charts/logging-operator/templates/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
docs/crds.md
pkg/resources/fluentd/config.go
pkg/resources/fluentd/configsecret.go
pkg/sdk/api/v1beta1/fluentd_types.go
pkg/sdk/api/v1beta1/logging_types.go

Separate fluentd log to stdout to avoid issues handling it accidentally
It can cause issues as these logs are not labeled properly

separate main fluentd log

---

charts/logging-demo/README.md
pkg/resources/fluentd/configsecret.go

FluentD default loglevel error -> info

---

docs/examples/logging_flow_with_multi_format.yaml
docs/logging-operator-monitoring.md

- multi_format parser example fix
- Monitoring Docs example deployment fix

Documentation fix

---

charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml

bump versions to prepare for 2.6.1

---

charts/logging-operator/templates/logging.banzaicloud.io_clusteroutputs.yaml
charts/logging-operator/templates/logging.banzaicloud.io_outputs.yaml
config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_outputs.yaml
docs/plugins/outputs/cloudwatch.md
pkg/sdk/model/output/cloudwatch.go

Assume Role Support

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator-logging/README.md
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
docs/crds.md
pkg/sdk/api/v1beta1/logging_types.go

- chart version bump 2.6.1 -> 2.7.0
- new fluentd image `fluentd-v1.7.4-alpine-12`

Release 2.7.0

---

ADOPTERS.md

doc: add hipages to adopter list

---

charts/logging-operator/Chart.yaml
charts/logging-operator/templates/deployment.yaml
charts/logging-operator/values.yaml

-> podSecurityContext back to the future

---

docs/crds.md

| Related tickets | fixes #X, partially #Y, mentioned in #Z
Add Fluentd scaling configuration to docs.
Add Fluentd scaling configuration to docs.
- [ x] User guide and development docs updated (if needed)

Add Fluentd scaling configuration to docs.

---

docs/security/manifests/deployment.yaml

Example deployment image fix

---

charts/logging-demo/templates/logging.yaml
charts/logging-demo/templates/tests/test-minio.yaml
charts/logging-operator-logging/templates/logging.yaml

Circle build refactor

---

charts/logging-operator-logging/Chart.yaml
charts/logging-operator-logging/templates/logging.yaml

chart/logging-operator-logging fix without TLS 

---

ADOPTERS.md

Codefactory

---

docs/quickstarts/es-nginx.md

Small edits and reformatting in quickstart/es-nginx.md

---

charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_outputs.yaml
docs/plugins/outputs/elasticsearch.md
pkg/sdk/model/output/elasticsearch.go
pkg/sdk/model/output/elasticsearch_test.go
pkg/sdk/model/output/zz_generated.deepcopy.go

| Related tickets | fixes #314 

Elastic Output config

---

docs/crds.md

Fix livenessDefaultCheck docs

---

docs/crds.md
docs/examples/logging_output_cloudwatch.yaml
docs/examples/logging_output_kinesis.yaml
docs/examples/logging_output_s3.yaml
docs/plugins/outputs/cloudwatch.md
docs/plugins/outputs/s3.md
docs/quickstarts/cloudwatch-nginx.md
docs/quickstarts/example-s3.md
hack/clusteroutput.yaml
hack/secret.yaml
pkg/sdk/model/output/cloudwatch.go
pkg/sdk/model/output/s3.go

Typo fix awsSecretAccesKey -> awsSecretAccessKey

---

charts/logging-operator/crds/logging.banzaicloud.io_clusterflows.yaml
charts/logging-operator/crds/logging.banzaicloud.io_flows.yaml
config/crd/bases/logging.banzaicloud.io_clusterflows.yaml
config/crd/bases/logging.banzaicloud.io_flows.yaml
docs/Readme.md
docs/blogs.md
docs/plugins/Readme.md
docs/plugins/filters/concat.md
docs/plugins/filters/dedot.md
docs/plugins/filters/detect_exceptions.md
docs/plugins/filters/geoip.md
docs/plugins/filters/parser.md
docs/plugins/filters/record_transformer.md
docs/plugins/filters/stdout.md
docs/plugins/filters/tagnormaliser.md
docs/quickstarts/README.md
pkg/sdk/model/filter/concat.go
pkg/sdk/model/filter/concat_test.go
pkg/sdk/model/filter/dedot.go
pkg/sdk/model/filter/dedot_test.go
pkg/sdk/model/filter/detect_exceptions.go
pkg/sdk/model/filter/geoip.go
pkg/sdk/model/filter/geoip_test.go
pkg/sdk/model/filter/parser.go
pkg/sdk/model/filter/record_transformer.go
pkg/sdk/model/filter/record_transformer_test.go
pkg/sdk/model/filter/stdout.go
pkg/sdk/model/filter/stdout_test.go
pkg/sdk/model/filter/tagnormaliser.go
pkg/sdk/model/filter/tagnormaliser_test.go

Filter test & Doc finetuning 

---

cmd/docs.go
docs/plugins/Readme.md
go.mod
pkg/docgen/docgen.go
pkg/docgen/docgen_test.go
pkg/docgen/plugins/index.go
pkg/docgen/plugins/plugins.go
pkg/docgen/testdata/sample.go

Make the docgen code reusable
We want to reuse it for generating basic CRD docs and in other projects as well

Docgen package

---

Makefile

Exclude ADOPTERS.md from  Makefile diff check 

---

pkg/sdk/api/v1beta1/logging_types.go

Bump version to v1.7.4-alpine-13

Update to latest fluentd container 

---

docs/deploy/README.md

Clarify docs on how to install the chart on helm3

---

go.mod
go.sum
pkg/sdk/go.mod
pkg/sdk/go.sum

Fixes a bug that causes using an emptyDir VolumeSource where a PVC should be used instead.

fix bug in KubernetesVolume.GetVolume

---

Makefile
config/samples/logging_v1alpha2_logging_default.yaml
docs/developers.md
docs/troubleshooting.md
go.mod
pkg/resources/fluentd/fluentd.go
pkg/resources/model/system.go
pkg/sdk/api/v1beta1/fluentbit_types.go
pkg/sdk/api/v1beta1/logging_types.go
pkg/sdk/api/v1beta1/suite_test.go
pkg/sdk/model/filter/grep.go
pkg/sdk/model/output/elasticsearch_test.go
pkg/sdk/model/output/kinesis_stream_test.go
pkg/sdk/model/render/fluent_test.go
pkg/sdk/model/types/stringmaps_test.go

| Related tickets | fixes #340, fixes #339, partially #341 
- Fixes tests and CI tools not running for the nested module.
- Fix rogue buffer path
- Fix rogue output id
- Add troubleshooting docs for kind

Fix nested module CI, fix several other bugs

---

charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_outputs.yaml
docs/plugins/outputs/kafka.md
pkg/sdk/model/output/kafka.go
pkg/sdk/model/output/kafka_test.go
pkg/sdk/model/output/zz_generated.deepcopy.go

| Bug fix?        | no |
Adds SSL options to Kafka output
My Kafka cluster requires client certs to ship logs.

Add SSL options to Kafka output

---

charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
docs/crds/v1beta1/fluentbit_types.md
docs/fluentbit.md
pkg/sdk/api/v1beta1/fluentbit_types.go

Fluentbit config key fix

---

charts/logging-operator/README.md

| Bug fix?        | no |
| New feature?    | no |
| API breaks?     | no |
| Deprecations?   | no |
| Related tickets | No ticket related |
This small PR is to update README.md file for `logging-operator` chart. It updates some default values and fix couple of typos.
Keep updated `logging-operator` chart documentation.

Update logging-operator chart README.md file

---

pkg/sdk/model/output/kinesis_stream.go
pkg/sdk/model/output/kinesis_stream_test.go

| Related tickets | fixes https://github.com/banzaicloud/logging-operator/issues/378

Fix Kinesis assume role config

---

docs/crds.md
docs/deploy/manifests/deployment.yaml

add missing match field description and links

---

docs/logging-operator-monitoring.md
docs/quickstarts/loki-nginx.md

Selector fix

---

pkg/sdk/model/output/s3.go
pkg/sdk/model/render/fluent_test.go

| Related tickets | fixes #362

Remove strict athuentication checking

---

charts/logging-operator-logging/values.yaml

Fix example by replacing deprecated fluentdPvcSpec with bufferStorageVolume

Chart example fix

---

charts/logging-operator-logging/Chart.yaml
charts/logging-operator-logging/templates/clusterflows.yaml
charts/logging-operator-logging/templates/clusteroutputs.yaml

Fix helm chart scoping

---

pkg/resources/model/system.go
pkg/sdk/model/render/fluent_test.go
pkg/sdk/model/render/test_helper.go
pkg/sdk/model/types/flow.go

| Related tickets | fixes #410 
This PR calculates flow label hash based on matches, flow name, and namespace

Fix flow label calculation

---

.circleci/config.yml
hack/test.sh

Fix the end-to-end test by locking down helm version

Lock down helm version

---

pkg/resources/model/system.go
pkg/sdk/plugins/plugin.go

Fix filter id

---

docs/plugins/outputs/loki.md
pkg/sdk/model/output/loki.go
pkg/sdk/model/output/zz_generated.deepcopy.go

| Related tickets | fixes #403

Loki output extract_kubernetes_labels default false fix

---

README.md
cmd/docs.go
docs/_index.md
docs/crds/_index.md
docs/crds/v1beta1/_index.md
docs/crds/v1beta1/clusterflow_types.md
docs/crds/v1beta1/clusteroutput_types.md
docs/crds/v1beta1/common_types.md
docs/crds/v1beta1/flow_types.md
docs/crds/v1beta1/fluentbit_types.md
docs/crds/v1beta1/fluentd_types.md
docs/crds/v1beta1/logging_types.md
docs/crds/v1beta1/output_types.md
docs/security/_index.md
pkg/sdk/api/v1beta1/clusterflow_types.go
pkg/sdk/api/v1beta1/clusteroutput_types.go
pkg/sdk/api/v1beta1/common_types.go
pkg/sdk/api/v1beta1/flow_types.go
pkg/sdk/api/v1beta1/fluentbit_types.go
pkg/sdk/api/v1beta1/fluentd_types.go
pkg/sdk/api/v1beta1/logging_types.go
pkg/sdk/api/v1beta1/output_types.go

Documentation refactor

---

docs/plugins/_index.md
pkg/sdk/model/output/elasticsearch.go
pkg/sdk/model/output/kafka.go
pkg/sdk/model/output/kinesis_stream.go
pkg/sdk/model/output/loki.go
pkg/sdk/model/output/newrelic.go
pkg/sdk/model/output/sumologic.go

Fluentd plugin version docs update

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml

Release 3.1.0-rc1 helm chart support

---

fluentd-image/v1.9/Dockerfile

fix prometheus-client version

---

pkg/sdk/resourcebuilder/component.go

Fix image version in resourcebuilder to reflect the actual image instead of the soon to be released version

fix resourcebuilder image tag

---

pkg/sdk/resourcebuilder/component.go

Uupdate to stable tag 3.1.0

---

docs/plugins/outputs/logz.md
docs/plugins/outputs/newrelic.md
pkg/sdk/model/output/logz.go
pkg/sdk/model/output/newrelic.go

Broken url fix

---

pkg/sdk/model/filter/grep.go
pkg/sdk/model/filter/parser.go
pkg/sdk/model/filter/prometheus.go
pkg/sdk/model/output/forward.go

* heading ids generated by hugo will always be lower cased
* heading ids must be specified for links, otherwise the generated id would contain the sanitized url as well

Hugo fixes

---

docs/crds/v1beta1/logging_types.md
docs/plugins/filters/grep.md
docs/plugins/filters/parser.md
docs/plugins/filters/prometheus.md
docs/plugins/outputs/elasticsearch.md
docs/plugins/outputs/forward.md

ReGenerate docs

---

fluentd-image/v1.7/healthy.sh
fluentd-image/v1.9/healthy.sh

FluentD default liveness check script parameter fix

---

pkg/resources/model/system.go
pkg/sdk/model/render/fluent_test.go

Fix hosts and container names generation.

fix missing attributes

---

pkg/sdk/resourcebuilder/component.go

Upgrade installer to latest version

Upgrade installer to latest version

---

fluentd-image/v1.10/Dockerfile
fluentd-image/v1.10/entrypoint.sh
fluentd-image/v1.10/fluent.conf
fluentd-image/v1.10/healthy.sh

New Fluentd image support 1.10

---

fluentd-image/v1.10/Dockerfile

Fix Fluentd 1.10.3 dependency

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator-logging/README.md
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml

Release 3.2.0

---

pkg/sdk/resourcebuilder/component.go

New sdk version 3.2.0

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

Update to version 3.2.1

---

fluentd-image/v1.10/Dockerfile

New fluentd version 1.10.3 -> 1.10.4

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml

Logging-operator 3.3.0 support

---

pkg/sdk/model/filter/concat.go

Add `name` and `weight` to generate frontmatter for hugo.

docs: fix hugo frontmatter

---

docs/plugins/_index.md
pkg/sdk/model/filter/prometheus.go
pkg/sdk/model/output/elasticsearch.go
pkg/sdk/model/output/loki.go
pkg/sdk/model/output/s3.go

plugin version docs update

---

docs/plugins/outputs/logdna.md
docs/security/_index.md
pkg/resources/fluentbit/daemonset.go
pkg/resources/fluentd/statefulset.go

- SeLinux support
- docs update
| Related tickets | fixes #514 

SeLinux support

---

fluentd-image/v1.11/Dockerfile
fluentd-image/v1.11/entrypoint.sh
fluentd-image/v1.11/fluent.conf
fluentd-image/v1.11/healthy.sh

Fluentd 1.11 support

---

charts/logging-operator-logging/README.md
charts/logging-operator/README.md
docs/crds/_index.md
docs/plugins/_index.md
pkg/sdk/api/v1beta1/logging_types.go
pkg/sdk/model/filter/prometheus.go
pkg/sdk/model/output/aws_elasticsearch.go
pkg/sdk/model/output/cloudwatch.go
pkg/sdk/model/output/datadog.go
pkg/sdk/model/output/elasticsearch.go
pkg/sdk/model/output/kafka.go
pkg/sdk/model/output/kinesis_firehose.go
pkg/sdk/model/output/kinesis_stream.go
pkg/sdk/model/output/loki.go
pkg/sdk/model/output/s3.go
pkg/sdk/model/output/splunk_hec.go

Fluentd 1.11.1

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

Chart version bump 3.4.0 -> 3.5.0

---

pkg/sdk/model/output/logdna.go

Add Hugo frontmater and replace example link with a remotely available one.

docs: fix hugo compatibility

---

docs/plugins/outputs/secret.md

Fix typo in secret docs fixes #535

Fix secret typo

---

fluentd-image/v1.11/Dockerfile

Downgrade Prometheus gem 2.1.0 -> 0.9.0

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

Release 3.5.1

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
docs/crds/v1beta1/clusterflow_types.md
docs/crds/v1beta1/flow_types.md
docs/crds/v1beta1/logging_types.md
pkg/sdk/resourcebuilder/component.go

Version 3.5.2

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

Release 3.6.0

---

config/dashboards/logging-dashboard_rev4.json

Grafana Dashboard

---

.github/workflows/ci.yml
.github/workflows/docker.yml
.github/workflows/docker_fluentd.yml
.licensei.toml
Makefile
charts/helm_testing.yaml

gh registry

---

README.md

References the newsletter in Readme.md

---

controllers/logging_controller.go
controllers/logging_controller_test.go
main.go
pkg/sdk/model/types/types.go

See individual commits for more info.

Small enhancements

---

pkg/resources/fluentd/appconfigmap.go
pkg/resources/fluentd/fluentd.go

| Related tickets | fixes #592

Configcheck security config

---

charts/logging-demo/templates/flow.yaml
charts/logging-operator-logging/values.yaml
config/samples/logging_v1alpha2_flow.yaml
config/samples/logging_v1alpha2_flow_custom.yaml
config/samples/logging_v1alpha2_multiflow.yaml
pkg/sdk/model/filter/concat.go
pkg/sdk/model/filter/dedot.go
pkg/sdk/model/filter/detect_exceptions.go
pkg/sdk/model/filter/geoip.go
pkg/sdk/model/filter/grep.go
pkg/sdk/model/filter/parser.go
pkg/sdk/model/filter/prometheus.go
pkg/sdk/model/filter/record_modifier.go
pkg/sdk/model/filter/record_transformer.go
pkg/sdk/model/filter/stdout.go
pkg/sdk/model/filter/tagnormaliser.go
pkg/sdk/model/filter/throttle.go

| Related tickets | fixes #596

Local Flow fix

---

charts/logging-operator-logging/README.md
charts/logging-operator/README.md
fluentd-image/v1.11/Dockerfile
pkg/sdk/api/v1beta1/logging_types.go
pkg/sdk/model/output/elasticsearch.go
pkg/sdk/model/output/kafka.go
pkg/sdk/model/output/logdna.go
pkg/sdk/model/output/loki.go
pkg/sdk/model/output/newrelic.go

Plugins: 
'fluent-plugin-elasticsearch' version `4.1.2` -> `4.2.2`
'fluent-plugin-grafana-loki' version '1.2.14' -> `1.2.15` 
'fluent-plugin-kafka' version `0.14.2` -> `0.15.2`
'fluent-plugin-logdna' version `0.3.1` -> `0.4.0`
'fluent-plugin-newrelic' version `1.1.8` -> `1.1.10` 
'fluent-plugin-prometheus' version `1.8.3` -> `1.8.4 `

FluentD 1.11.2 -> 1.11.4

---

.github/workflows/docker_fluentd.yml

Signed-off-by: Nandor Kracser <bonifaido@gmail.com>
Unfortunately, GitHub tag filters are not real regexp: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

ci: tag push regexp fix

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

Release 3.7.1

---

pkg/sdk/model/output/s3.go
pkg/sdk/model/render/fluent_test.go

unnecessary '/' path delimiter removed

s3output one-eye format keytemplate fix

---

charts/logging-operator-logging/values.yaml

| Related tickets | fixes #618

Kafka output example fix

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

Release 3.7.3

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

Release 3.8.0

---

charts/logging-operator/templates/service.yaml

| Related tickets | n/a
Minor typo fix.
`yamllint` complains :smile: 
n/a

Fix whitespace typo in helm chart

---

charts/logging-demo/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

Release 3.8.1

---

charts/logging-operator-logging/README.md
charts/logging-operator/README.md
fluentd-image/v1.11/Dockerfile
pkg/sdk/api/v1beta1/logging_types.go

New sumologic filters

---

ADOPTERS.md

Adds Storm Reply to adopters.md

---

charts/logging-operator-logging/README.md
charts/logging-operator/README.md
fluentd-image/v1.11/Dockerfile
pkg/sdk/api/v1beta1/logging_types.go
pkg/sdk/model/output/logz.go

| Related tickets | fixes #659 

Logzio output fix

---

pkg/sdk/model/filter/detect_exceptions.go

Fixes detectExceptions example according to https://github.com/banzaicloud/logging-operator-docs/issues/19

Fix detectExceptions example

---

charts/logging-operator/templates/clusterrolebinding.yaml

| Related tickets | fixes #672

Chart api version fix

---

charts/logging-operator-logging/README.md
charts/logging-operator/README.md
fluentd-image/v1.11/Dockerfile
pkg/sdk/api/v1beta1/logging_types.go

Alpine image update

---

fluentd-image/v1.11/Dockerfile
pkg/sdk/api/v1beta1/logging_types.go
pkg/sdk/model/filter/prometheus.go
pkg/sdk/model/output/cloudwatch.go
pkg/sdk/model/output/elasticsearch.go
pkg/sdk/model/output/kafka.go
pkg/sdk/model/output/logz.go
pkg/sdk/model/output/redis.go
pkg/sdk/model/output/sumologic.go

Plugin version update + webrick update 

---

charts/logging-operator/Chart.yaml
charts/logging-operator/templates/psp.yaml

| Related tickets | fixes #684, fixes #652
Fix the default seccomp profile name.
It was broken in #652.

Fix #652 regression

---

pkg/sdk/model/filter/parser.go

Fixes broken description in the parser filter

---

charts/logging-operator-logging/Chart.yaml
charts/logging-operator-logging/templates/logging.yaml
charts/logging-operator-logging/values.yaml

Adds globalFilters to the logging to the logging object.

Add globalFilters to logging chart

---

pkg/sdk/api/v1beta1/logging_types.go

Add basic documentation for root Logging object.

add logging resource documentation

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

Bump image versions to the latest 3.9.1 that contains some fixes on top of 3.9.0

Upgrade image to 3.9.1

---

charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/templates/deployment.yaml
charts/logging-operator/values.yaml

Add `podLabels` value
Custom Pod labels are needed

Add podLabels value

---

fluentd-image/v1.11/Dockerfile

| Related tickets | fixes #707 

Fluentd base alpine image 3.13.0 -> 3.13.4

---

NOTICE

License notice to reflect Cisco copyright

Licence notice

---

pkg/resources/fluentbit/configsecret.go
pkg/resources/nodeagent/configsecret.go

| Related tickets | fixes #679 

Default fluentbit keepalive config

---

pkg/sdk/model/output/redis.go

To fix https://github.com/banzaicloud/logging-operator-docs/pull/69 in the source

Fixes title of Redis output in docs

---

charts/logging-operator-logging/README.md
charts/logging-operator/README.md
fluentd-image/v1.11/Dockerfile
pkg/sdk/api/v1beta1/logging_types.go

Splunk prometheus client 2.1 support

---

pkg/sdk/model/output/http.go
pkg/sdk/model/output/s3.go

That prevent merging updates to the website

Fixes broken doclinks in s3 and http outputs

---

pkg/resources/fluentd/fluentd.go

Intermediate fixes around the drainer logic

Drain review

---

docs/volume-drainer.md

Add design and manual test setup doc. Test steps are still missing.

Drain review - doc

---

docs/volume-drainer.md
pkg/resources/fluentd/appconfigmap.go
pkg/resources/fluentd/fluentd.go

Terminate the drainer job and remove the placeholder pod blocking the statefulset from creating its pods when it's upscaled.
Without this, the statefulset is blocked from creating all its pods when upscaled until all drainer jobs have finished.

Abort draining on upscale

---

pkg/sdk/model/output/syslog.go
pkg/sdk/model/output/syslog_test.go

Fix default format on empty configuration

Fix syslog defaults

---

charts/logging-demo/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

Release 3.12.0

---

pkg/sdk/resourcebuilder/component.go

Operator component arg added

---

docs/volume-drainer.md

Fixes the volume drainer example flow
It reprocessed it's own logs

Fix volume drainer example flow

---

pkg/sdk/model/output/redis.go

Fix dox title in redis.go

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator-logging/README.md
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/api/v1beta1/logging_types.go
pkg/sdk/model/filter/concat.go
pkg/sdk/model/filter/enhance_k8s.go
pkg/sdk/model/filter/prometheus.go
pkg/sdk/model/output/aws_elasticsearch.go
pkg/sdk/model/output/cloudwatch.go
pkg/sdk/model/output/datadog.go
pkg/sdk/model/output/elasticsearch.go
pkg/sdk/model/output/kafka.go
pkg/sdk/model/output/kinesis_firehose.go
pkg/sdk/model/output/kinesis_stream.go
pkg/sdk/model/output/newrelic.go
pkg/sdk/model/output/s3.go
pkg/sdk/model/output/splunk_hec.go
pkg/sdk/model/output/syslog.go
pkg/sdk/resourcebuilder/component.go

Release 3.13

---

pkg/sdk/resourcebuilder/component.go

Logging-operator specific Prometheus recording rules for Fluentd buffer metrics.
These rules should provide metrics that are useful when monitoring Fluentd instances.

add logging-operator specific PrometheusRule to resource builder

---

pkg/resources/fluentd/prometheusrules.go

FluentD prometheus buffer prediction alert

---

charts/logging-operator-logging/README.md
charts/logging-operator/README.md
fluentd-image/v1.13/Dockerfile
pkg/sdk/api/v1beta1/logging_types.go
pkg/sdk/model/filter/prometheus.go
pkg/sdk/model/output/elasticsearch.go
pkg/sdk/model/output/kafka.go
pkg/sdk/model/output/newrelic.go
pkg/sdk/model/output/s3.go

Fluentd update 1.13.3

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

Release 3.14

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

| Related tickets | fixes #815

Version 3.14.1

---

charts/logging-operator-logging/README.md
charts/logging-operator/README.md
pkg/sdk/api/v1beta1/logging_types.go

- fluent-plugin-label-router 0.2.10
| Related tickets | fixes #827

Fluentd 1.13.3-alpine-5

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator-logging/README.md
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/api/v1beta1/logging_types.go
pkg/sdk/model/output/elasticsearch.go
pkg/sdk/model/output/kafka.go
pkg/sdk/model/output/kinesis_firehose.go
pkg/sdk/model/output/kinesis_stream.go
pkg/sdk/model/output/splunk_hec.go
pkg/sdk/resourcebuilder/component.go

New Fluend Plugins: 
fluent-plugin-detect-exceptions' version '0.0.13' -> '0.0.14'
fluent-plugin-elasticsearch' version '5.1.1' -> '5.1.4'
fluent-plugin-kafka'version '0.17.2' -> '0.17.3'
fluent-plugin-kinesis' version '3.4.1' ->  '3.4.2'
fluent-plugin-splunk-hec' version '1.2.7' -> '1.2.8'

Release 3.16.0

---

charts/logging-operator-logging/README.md
charts/logging-operator/README.md
fluentd-image/v1.13/Dockerfile
pkg/sdk/api/v1beta1/logging_types.go

| Related tickets | fixes #887

fluent-plugin-detect-exceptions permission fix

---

config/samples/extensions/logging-extensions_v1alpha1_eventtailer_with_pvc.yaml
config/samples/extensions/logging-extensions_v1alpha1_eventtailer_without_pvc.yaml
config/samples/extensions/logging-extensions_v1alpha1_hosttailer.yaml
config/samples/extensions/logging-extensions_v1alpha1_webhook.yaml
config/samples/extensions/testpod.yaml
config/samples/extensions/testpod_annotated.yaml
config/samples/extensions/testpod_annotated_multicontainer.yaml

examples added from extensions repo

extensions examples added

---

pkg/sdk/logging/model/output/cloudwatch.go

Add Format SubDirectives to CloudWatch.
It is currently not plugged in.

Add Format SubDirective to CloudWatch output

---

cmd/docs.go

generated docs upgrade for extensions

generated CRD docs update for extensions

---

pkg/sdk/resourcebuilder/component.go

release-3.17.0

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/logging/model/output/datadog.go
pkg/sdk/logging/model/output/loki.go
pkg/sdk/logging/model/output/splunk_hec.go

Fluend plugin, chart version bump (3.17.0)

---

pkg/resources/fluentbit/prometheusrules.go

| Related tickets | fixes #904

FluentBit PrometheusRule job name fix

---

Makefile

increase e2e test timeout 10m -> 20m

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

Release version bump 3.17.1

---

docs/scaling.md

This PR fixes the indentation in scaling.md docs. 
Because applying the example from docs is not working :)

Fix indentation in scaling.md docs

---

pkg/resources/fluentd/statefulset.go

| Related tickets | fixes https://github.com/banzaicloud/logging-operator/issues/682
Fix the default fluentd readiness probe that was not correctly executing. Pass the bash payload as a single argument after the `sh`, `-c`.
The readiness probe was always returning true.

fix(fluentd): update default readiness checks

---

ADOPTERS.md

Add Carrefour to adopters

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

Release 3.17.3

---

charts/logging-operator-logging/values.yaml

| Related tickets | fixes #957
Disable EventTailer and HostTailer by default
It was enabled in the latest release

fix(chart): disable EventTailer and HostTailer by default

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

Release version update 3.17.3  -> 3.17.4

---

.circleci/config.yml
Makefile
fluentd-image/e2e-test/Dockerfile
fluentd-image/e2e-test/entrypoint.sh
fluentd-image/e2e-test/fluent.conf
fluentd-image/e2e-test/healthy.sh
fluentd-image/v1.10/healthy.sh
fluentd-image/v1.11/healthy.sh
fluentd-image/v1.12/healthy.sh
fluentd-image/v1.13/healthy.sh
fluentd-image/v1.14/healthy.sh
fluentd-image/v1.7/healthy.sh
fluentd-image/v1.9/healthy.sh

Fix of e2e fluentd image build
Failed e2e-test in CircleCI

E2E fluentd build fix

---

fluentd-image/v1.14/Dockerfile

| Related tickets | fixes #907

Splunk http lib fix

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/logging/model/output/kafka.go
pkg/sdk/logging/model/output/sumologic.go
pkg/sdk/resourcebuilder/component.go

Release 3.17.5

---

pkg/sdk/logging/model/output/http.go

| Related tickets | fixes #962
https://github.com/fluent/fluentd/pull/2809

Fluentd retryable_response_codes doc extension

---

pkg/sdk/extensions/api/v1alpha1/filetailer.go

Fluentbit Buffer_Chunk_Size parameter support

---

main.go

| Related tickets | fixes #977

Zap logging output format parameter support

---

pkg/sdk/logging/api/v1beta1/fluentbit_types.go
pkg/sdk/logging/model/filter/detect_exceptions.go
pkg/sdk/logging/model/filter/prometheus.go
pkg/sdk/logging/model/output/aws_elasticsearch.go
pkg/sdk/logging/model/output/cloudwatch.go
pkg/sdk/logging/model/output/elasticsearch.go
pkg/sdk/logging/model/output/file.go
pkg/sdk/logging/model/output/gelf.go
pkg/sdk/logging/model/output/http.go
pkg/sdk/logging/model/output/kafka.go
pkg/sdk/logging/model/output/kinesis_firehose.go
pkg/sdk/logging/model/output/kinesis_stream.go
pkg/sdk/logging/model/output/logdna.go
pkg/sdk/logging/model/output/logz.go
pkg/sdk/logging/model/output/loki.go
pkg/sdk/logging/model/output/newrelic.go
pkg/sdk/logging/model/output/opensearch.go
pkg/sdk/logging/model/output/redis.go
pkg/sdk/logging/model/output/s3.go
pkg/sdk/logging/model/output/splunk_hec.go
pkg/sdk/logging/model/output/sqs.go
pkg/sdk/logging/model/output/sumologic.go
pkg/sdk/logging/model/output/syslog.go

- Fix source code so doc generator runs
- Fix for issue#899
- Minor fixes 
@ahma: I've added doc stubs to ```type Operation struct ``` in pkg/sdk/logging/api/v1beta1/fluentbit_types.go, but we should add a proper description

Fix doc generator

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml

Release 3.17.6

---

pkg/resources/fluentd/statefulset.go

| Related tickets | fixes #1013 
Update the custom runner commands args to correctly pass the node_exporter command.

fix(bufferMetricsSidecar): update custom runner command args format 

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

Release 3.17.7

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

Release 3.17.8

---

charts/logging-operator-logging/templates/eventtailer.yaml
charts/logging-operator-logging/values.yaml

| Related tickets | fixes #1061 
Fix the storageClass definition for eventTailer in logging-operator-logging helm chart 
It is broken.

fix(helm): typo in eventTailer storageClassName

---

ADOPTERS.md

Add KubeGems to adopters

---

.circleci/config.yml
hack/test.sh

Minikube replaced by Kind, K8S version bumped to v1.17.17

Fix e2e tests on CircleCi

---

pkg/sdk/logging/api/v1beta1/logging_types.go

Node-exporter image tag fix

---

node-exporter-image/Dockerfile
pkg/resources/fluentbit/daemonset.go
pkg/sdk/logging/api/v1beta1/logging_types.go

Node-exporter text export fix

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

Release 3.17.9

---

pkg/sdk/logging/model/output/aws_elasticsearch.go

Fixes https://github.com/banzaicloud/logging-operator-docs/issues/65

Fix Amazon Elasticsearch example

---

controllers/logging/logging_controller_test.go
pkg/resources/model/system.go

Add Namespace to "output not found" log
Gives more visibility on "output not found" errors

chore: add flow/output namespace to error logs

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
pkg/sdk/resourcebuilder/component.go

- chart version bump
- sub version bump

Release 3.17.10

---

pkg/resources/fluentbit/buffervolumeprometheusrules.go

Rename `fluentbitBufferSize` alert to `FluentbitBufferSize`
There was a drift between the two level of alerts (warning / critical)

chore: capitalize FluentbitBufferSize alert name

---

.github/workflows/e2e.yml

| Bug fix?        | no/yes
| New feature?    | no/yes
| API breaks?     | no/yes
| Deprecations?   | no/yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z

fix(e2e): fix kind cluster setup

---

pkg/resources/syslogng/syslogng.go
pkg/sdk/resourcebuilder/component.go

syslog-ng 4.0.1

---

pkg/sdk/resourcebuilder/component.go

logging operator's version bump (4.0.0-rc17) in resourcebuilder (pkg/sdk)

logging-operator version bump 4.0.0-rc17

---

pkg/sdk/resourcebuilder/component.go

release 4.0-rc18

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml

charts updated for logging operator version 4.0.0-rc17 (hosttailer imps fix, operator-tools update)

charts 4.0.0-rc17

---

charts/logging-operator/Chart.yaml
pkg/sdk/resourcebuilder/component.go

Release 4.0-rc19

---

pkg/sdk/resourcebuilder/component.go

Signed-off-by: Mark Sagi-Kazar <mark.sagikazar@gmail.com>

chore: fix linter violations

---

.github/workflows/ci.yaml
.github/workflows/e2e.yaml

Signed-off-by: Mark Sagi-Kazar <mark.sagikazar@gmail.com>

Generic improvements to CI

---

e2e/charts/logging-operator-logging/values.yaml

after sync of https://github.com/kube-logging/helm-charts/pull/16

 chore(e2e/charts): remove too many blank lines on values.yaml

---

pkg/resources/syslogng/syslogng.go

chore(deps): bump syslogng-reload

---

.github/stale.yml

Enable stale bot with default settings to clean up outdated issues.

chore(stale): enable stale bot

---

e2e/charts/logging-operator-logging/Chart.yaml
e2e/charts/logging-operator/Chart.yaml

together with https://github.com/kube-logging/helm-charts/pull/17

fix(e2e/charts): update to operator version 4.1.0

---

pkg/resources/fluentd/statefulset.go

Test this with:
```
make install
helm repo add kube-logging https://kube-logging.github.io/helm-charts
helm install logging-operator-logging kube-logging/logging-operator-logging
```
Use the following config for fluentd (storageClassName should be something supported on your provider, I've tested this on minikube):
```
fluentd:
extraVolumes:
- containerName: fluentd
path: /data
volume:
pvc:
source:
claimName: fluentd-data
spec:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 1Gi
storageClassName: standard
volumeMode: Filesystem
```
Then simply run the operator and see if the pvcs and the fluentd pod has been created properly
```
make run
```
Fixes: #1057 #1063

fix: add missing logic to handle PVCs for extraVolumes

---

renovate.json

chore(deps): delay k8s minor upgrades one month after release

---

pkg/resources/fluentd/drainjob.go

fix: add uncompress init container to fluentd drainer job

---

pkg/resources/fluentd/fluentd.go

fix: restore lost fluentd config error check

---

.github/workflows/ci.yaml
.github/workflows/codeql.yml
.github/workflows/e2e.yaml

ci: extend ci for maintenance release branches

---

ADOPTERS.md

adopters: add acquia and cisco

---

e2e/syslog-ng-aggregator/syslog_ng_aggregator_test.go
e2e/volumedrain/volumedrain_test.go
pkg/resources/fluentbit/config.go
pkg/resources/fluentbit/configsecret.go
pkg/resources/fluentbit/daemonset.go

fix: use a separate path to mount custom config for the operator

---

e2e/go.mod
e2e/syslog-ng-aggregator/syslog_ng_aggregator_test.go
pkg/sdk/extensions/extensionsconfig/config.go
pkg/sdk/resourcebuilder/component.go

Pull changes in `release-4.2` into master (ideally this will be automated with github actions)
(Please don't update the branch)

Merge changes from release-4.2

---

e2e/charts/logging-operator-logging/Chart.yaml
e2e/charts/logging-operator/Chart.yaml

- fix: do not refer to upstream config item to avoid hiding fluentbit configuration, also use absolute path in the config
- chore: sync chart changes

sync chart changes

---

charts/logging-operator/templates/logging_fluentbit.yaml

Inject `.Values.logging.loggingRef` into FluentbitAgent if not given in `.Values.logging.fluentbit.loggingRef`

fix(helm): inject loggingRef into FluentbitAgent

---

charts/logging-operator/README.md
charts/logging-operator/templates/_helpers.tpl
charts/logging-operator/values.yaml
pkg/sdk/logging/api/v1beta1/logging_types.go

Reduce load on DNS stack by explicitly disabling recursive search lookups.

feat: update cluster domain to force direct resolution

---

charts/logging-operator/README.md
charts/logging-operator/values.yaml

An old unused value is still present in the value file & docs.

fix(helm): remove duplicate watchNamespace value

---

.github/workflows/ci.yaml

ci: fix go mod cache by reordering steps

---

pkg/sdk/logging/api/v1beta1/logging_types.go

Bump to latest version
https://github.com/fluent/fluent-bit/releases

deps: upgrade fluent-bit to 2.1.8

---

controllers/logging/logging_controller.go

chore(syslog-ng): limit maxConnections and tune the node based increments

---

charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_outputs.yaml
docs/configuration/plugins/outputs/oss.md
pkg/sdk/logging/model/output/oss.go
pkg/sdk/logging/model/output/oss_test.go
pkg/sdk/logging/model/output/zz_generated.deepcopy.go

Fixes #1361 
available at `ghcr.io/aslafy-z/logging-operator:aliyun-access-key-secret`

fix: typo in aliyun access_key_secret property

---

config/samples/mulitenant-hard/README.md
config/samples/mulitenant-hard/logging/receiver-infra.yaml
config/samples/mulitenant-hard/logging/tenant-a-logging.yaml
config/samples/mulitenant-hard/logging/tenant-a-user.yaml
config/samples/mulitenant-hard/logging/tenant-b-logging.yaml
config/samples/mulitenant-hard/logging/tenant-b-user.yaml

chore(sample): add hard multi-tenant config example

---

charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_outputs.yaml
docs/configuration/crds/v1beta1/output_types.md
docs/configuration/plugins/outputs/kinesis_firehose.md
pkg/sdk/logging/api/v1beta1/output_types.go
pkg/sdk/logging/api/v1beta1/zz_generated.deepcopy.go
pkg/sdk/logging/model/output/kinesis_firehose.go

Fixes https://github.com/kube-logging/logging-operator/issues/1479

fix: add missing KinesisFirehose output config entry

---

main.go

Fixes #1428 by parsing out the number part of version-like strings, for example "27+" which happens to be the minor version returned by the API server on EKS

fix: server version detection for handling psp

---

pkg/resources/eventtailer/statefulset.go
pkg/sdk/extensions/extensionsconfig/config.go
pkg/sdk/logging/api/v1beta1/logging_types.go

https://github.com/kube-logging/logging-operator/pull/1482

chore: image updates

---

charts/logging-operator/crds/logging.banzaicloud.io_syslogngclusteroutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_syslogngoutputs.yaml
config/crd/bases/logging.banzaicloud.io_syslogngclusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_syslogngoutputs.yaml
docs/configuration/plugins/syslogng-outputs/mongodb.md
pkg/sdk/logging/model/syslogng/config/output_tests/mongodb_test.go
pkg/sdk/logging/model/syslogng/output/mongodb.go
pkg/sdk/logging/model/syslogng/output/zz_generated.deepcopy.go

See this gist for a really minimal MongoDB setup:
https://gist.github.com/OverOrion/c93855f0f8c1187ef6ee6ef98547fa51

bug(mongodb): fix `uri` field to be secret, remove invalid `compaction` field

---

controllers/logging/tenant_test.go

test(tenants): fix intermittent test and remove obsolete one

---

charts/logging-operator/crds/logging.banzaicloud.io_syslogngclusteroutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_syslogngoutputs.yaml
config/crd/bases/logging.banzaicloud.io_syslogngclusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_syslogngoutputs.yaml
docs/configuration/plugins/syslogng-outputs/s3.md
pkg/sdk/logging/model/syslogng/config/output_tests/s3_test.go
pkg/sdk/logging/model/syslogng/output/s3.go
pkg/sdk/logging/model/syslogng/output/zz_generated.deepcopy.go

Signed-off-by: Kristof Gyuracz <kristof.gyuracz@gmail.com>

fix(syslogng-s3-output): change objectkey field to string

---

Dockerfile

WIP: add `maintainer`, `authors` and `vendor` values.
Closes #1505.

image: add OCI-labels

---

go.mod
pkg/webhook/podhandler/podhandler.go

Needs https://github.com/kube-logging/logging-operator/pull/1494 before merging.
Fixes #1444.

Make mutating webhook idempotent

---

controllers/logging/logging_controller.go
pkg/sdk/logging/api/v1beta1/logging_types.go

Configurable maxconnections fix for syslog-ng

---

charts/logging-operator/templates/service_monitor.yaml

Fixes https://github.com/kube-logging/logging-operator/issues/1559

Fix metricRelabelings templating in helm chart

---

Dockerfile
Makefile

feat: debug image

---

charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_outputs.yaml
docs/configuration/plugins/outputs/azurestore.md
pkg/sdk/logging/model/output/azurestore.go

Adding AzureCloud field optionally usable by plugins

---

pkg/resources/syslogng/syslogng.go

See original issue for details:
https://github.com/syslog-ng/syslog-ng/issues/4697

axosyslog: use version with s3 fix

---

README.md

openssf badge update

---

.github/release.yml
renovate.json

chore: define release note labels

---

.github/release.yml

- chore: define release note labels
- chore: fix dependency label for release notes

release labels

---

charts/logging-operator/templates/service_monitor.yaml

fixes https://github.com/kube-logging/logging-operator/issues/1630

chore(chart): check CRDs available before installing ServiceMonitor

---

docs/configuration/plugins/_index.md
docs/configuration/plugins/filters/enhance_k8s.md
pkg/sdk/logging/model/filter/enhance_k8s.go

fixes https://github.com/kube-logging/kube-logging.github.io/issues/210

fix doc link for enhance-k8s-metadata plugin

---

docs/configuration/crds/v1beta1/_index.md
docs/configuration/crds/v1beta1/fluentd_config_types.md
docs/configuration/crds/v1beta1/fluentd_types.md
docs/configuration/crds/v1beta1/syslogng_config_types.md
docs/configuration/crds/v1beta1/syslogng_types.md
go.work.sum
pkg/sdk/logging/api/v1beta1/fluentd_config_types.go
pkg/sdk/logging/api/v1beta1/fluentd_types.go
pkg/sdk/logging/api/v1beta1/syslogng_config_types.go
pkg/sdk/logging/api/v1beta1/syslogng_types.go

- chore(docs): move fluentd config to separate file
- chore(docs): move syslogng config to separate file

config type move

---

pkg/resources/model/repository.go

fix: add namespace filter when listing aggregator configs

---

pkg/resources/model/repository.go

fix: add namespace filter when listing aggregator configs (#1644)

---

e2e/go.mod
e2e/go.sum
go.mod
go.sum
pkg/sdk/go.mod
pkg/sdk/go.sum
pkg/sdk/logging/model/syslogng/config/go.mod
pkg/sdk/logging/model/syslogng/config/go.sum

chore: upgrade protobuf dep

---

pkg/resources/fluentbit/configsecret.go
pkg/resources/fluentbit/tenants.go

fix tenant aggregation detection

---

controllers/logging/logging_controller.go
pkg/resources/fluentbit/configsecret.go
pkg/resources/fluentbit/fluentbit.go
pkg/resources/fluentbit/tenants.go
pkg/resources/model/resources.go

fix to make detached aggregators work when generating fluentbit tenants

---

e2e/go.mod
e2e/go.sum
go.mod
go.sum
pkg/sdk/go.mod
pkg/sdk/go.sum
pkg/sdk/logging/model/syslogng/config/go.mod
pkg/sdk/logging/model/syslogng/config/go.sum

chore(deps): update protobuf

---

controllers/logging/logging_controller.go

chore: hide flow config in the logs by default

---

e2e/fluentd-aggregator/fluentd_aggregator_test.go

e2e test for config checks

---

main.go

Signed-off-by: Szilard Parrag <szilard.parrag@axoflow.com>

fix(operator): remove invalid container runtime log message

---

pkg/sdk/extensions/extensionsconfig/config.go
pkg/sdk/logging/api/v1beta1/logging_types.go

fluentbit: upgrade default image version to latest

---

docs/terraform-syslog-ng-s3.md

Add sample to docs which shows how to deploy logging-operator with terraform/OpenTofu.

Add docs for deploying logging-operator with terraform

---

charts/logging-operator/crds/logging.banzaicloud.io_fluentbitagents.yaml
charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_fluentbitagents.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
config/samples/syslog-ng-retry.yaml
docs/configuration/crds/v1beta1/fluentbit_types.md
pkg/resources/fluentbit/config.go
pkg/resources/fluentbit/configsecret.go
pkg/sdk/logging/api/v1beta1/fluentbit_types.go

Add retry limit for tcp output

---

config/samples/multitenant-routing-2/logging/tenant-b-logging.yaml
config/samples/syslog-ng-retry.yaml
config/samples/syslog-ng-simple.yaml

chore: remove trace log setting from examples to avoid suggesting a bad practice

---

pkg/resources/fluentbit/daemonset.go

feat: insert configmapreloader imagepullsecrets in fluentbit ds

---

charts/logging-operator/templates/service.yaml

Fixes #1791  respect http.service.type

fix: http.service.type not being respect

---

config/crd/kustomization.yaml
config/crd/patches/webhook_in_clusterflows.yaml
config/crd/patches/webhook_in_clusteroutputs.yaml
config/crd/patches/webhook_in_flows.yaml
config/crd/patches/webhook_in_fluentbits.yaml
config/crd/patches/webhook_in_fluentds.yaml
config/crd/patches/webhook_in_loggings.yaml
config/crd/patches/webhook_in_outputs.yaml
config/default/kustomization.yaml

- This PR handles breaking-changes that occoured in latest kustomize releases
- The changes are backwards compatible with older releases (Tested with v4.3.0)

fix: adjust kustomize config for latest version

---

e2e/go.mod
e2e/go.sum
e2e/logging_metrics_monitoring/logging_metrics_monitoring_test.go
pkg/resources/fluentbit/prometheusrules.go
pkg/resources/fluentbit/service.go
pkg/resources/nodeagent/service.go

feat(e2e): add metrics e2e-test

---

charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_outputs.yaml
docs/configuration/plugins/outputs/opensearch.md
pkg/sdk/logging/model/output/opensearch.go

Adds support for [remove_keys](https://github.com/fluent/fluent-plugin-opensearch?tab=readme-ov-file#remove_keys) to the opensearch plugin.

OpenSearch remove_keys parameter support

---

pkg/resources/fluentd/outputsecret.go

fix: nil ptr panic on empty secrets slice during cfg-check

---

pkg/sdk/logging/model/syslogng/config/config.go
pkg/sdk/logging/model/syslogng/config/flow.go

feat: add syslogng flow-output validation

---

charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_fluentbitagents.yaml
charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_fluentdconfigs.yaml
charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
charts/logging-operator/crds/logging.banzaicloud.io_fluentbitagents.yaml
charts/logging-operator/crds/logging.banzaicloud.io_fluentdconfigs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_fluentbitagents.yaml
config/crd/bases/logging.banzaicloud.io_fluentdconfigs.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
docs/configuration/crds/v1beta1/fluentbit_types.md
docs/configuration/crds/v1beta1/fluentd_types.md
pkg/resources/fluentbit/config.go
pkg/resources/fluentbit/configsecret.go
pkg/resources/fluentd/config.go
pkg/resources/fluentd/configsecret.go
pkg/sdk/logging/api/v1beta1/common_types.go
pkg/sdk/logging/api/v1beta1/fluentbit_types.go
pkg/sdk/logging/api/v1beta1/fluentd_types.go

fixes: https://github.com/kube-logging/logging-operator/pull/1844 https://github.com/kube-logging/logging-operator/pull/1836

feat: support enable ipv6 

---

pkg/sdk/extensions/extensionsconfig/config.go
pkg/sdk/extensions/extensionsconfig/config_test.go
pkg/sdk/logging/api/v1beta1/logging_types.go

fix: use fully qualified images

---

charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_fluentdconfigs.yaml
charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
charts/logging-operator/crds/logging.banzaicloud.io_fluentdconfigs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_fluentdconfigs.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
docs/configuration/crds/v1beta1/fluentd_types.md
pkg/resources/fluentd/appconfigmap.go
pkg/resources/fluentd/statefulset.go
pkg/sdk/logging/api/v1beta1/fluentd_types.go

Fixes: https://github.com/kube-logging/logging-operator/issues/791

feat(config-reloader): enable setting graceful reload webhook

---

main.go

fix watch namespace for secrets and cluster resources

---

Makefile
charts/logging-operator/templates/clusterrole.yaml
charts/logging-operator/templates/userrole.yaml

Fixes: [#1936](https://github.com/kube-logging/logging-operator/issues/1936)

fix missing labels in clusterrole and userrole template

---

charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_fluentbitagents.yaml
charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
charts/logging-operator/crds/logging.banzaicloud.io_fluentbitagents.yaml
charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_fluentbitagents.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
docs/configuration/crds/v1beta1/fluentbit_types.md
pkg/resources/fluentbit/daemonset.go
pkg/sdk/logging/api/v1beta1/fluentbit_types.go
pkg/sdk/logging/api/v1beta1/logging_types.go
pkg/sdk/logging/api/v1beta1/zz_generated.deepcopy.go

Fixes https://github.com/kube-logging/logging-operator/issues/1955

feat: add varlibcontainers volume as optional

---

.github/workflows/config-reloader.yaml
.github/workflows/fluentd-images.yaml
.github/workflows/syslog-ng-reloader.yaml

https://github.com/kube-logging/logging-operator/actions/runs/13698411821

fix(ci): permissions

---

.github/workflows/artifacts.yaml
.github/workflows/ci.yaml
.github/workflows/config-reloader.yaml
.github/workflows/e2e.yaml
.github/workflows/fluentd-images.yaml
.github/workflows/syslog-ng-reloader.yaml

chore(deps): update CI deps

---

README.md

- Remove underline
- Add target _blank
- Add missing ALT text
- Fix goreport link

chore: update readme header

---

controllers/logging/logging_controller.go
controllers/logging/telemetry_controller_controller.go

fix(logging_controller): reconcile child resources

---

charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_clusterflows.yaml
charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_flows.yaml
charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
charts/logging-operator/crds/logging.banzaicloud.io_clusterflows.yaml
charts/logging-operator/crds/logging.banzaicloud.io_flows.yaml
charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_clusterflows.yaml
config/crd/bases/logging.banzaicloud.io_flows.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
docs/configuration/plugins/filters/parser.md
pkg/sdk/logging/model/filter/parser.go
pkg/sdk/logging/model/filter/parser_test.go

Fix https://github.com/kube-logging/logging-operator/issues/2005

Add format_key and format_name in ParseSection and SingleParseSection

---

ADOPTERS.md
CONTRIBUTING.md
README.md
charts/logging-operator/README.md
charts/logging-operator/README.md.gotmpl
charts/logging-operator/values.yaml
docs/configuration/plugins/outputs/kafka.md
docs/configuration/plugins/outputs/loki.md
docs/configuration/plugins/outputs/relabel.md
docs/scaling.md
docs/syslogng-quickstart.md
docs/volume-drainer.md
main.go
pkg/sdk/logging/model/output/kafka.go
pkg/sdk/logging/model/output/loki.go
pkg/sdk/logging/model/output/relabel.go

chore: standardize naming to "Logging operator"

---

charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_clusteroutputs.yaml
charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_outputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_outputs.yaml
docs/configuration/plugins/outputs/forward.md
pkg/sdk/logging/model/output/forward.go

add compress field to forward output
https://docs.fluentd.org/output/forward#how-to-enable-gzip-compression

feat: add compress field to forward output

---

charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_fluentbitagents.yaml
charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
charts/logging-operator/crds/logging.banzaicloud.io_fluentbitagents.yaml
charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_fluentbitagents.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
docs/configuration/crds/v1beta1/fluentbit_types.md
pkg/resources/fluentbit/daemonset.go
pkg/sdk/logging/api/v1beta1/fluentbit_types.go
pkg/sdk/logging/api/v1beta1/logging_types.go
pkg/sdk/logging/api/v1beta1/zz_generated.deepcopy.go

I want to make the mount of /var/log optional as there might be users of k8s clusters which do not allow mounting host volumes but provide different ways to collect host logs.

feat: add parameter to disable mount of /var/log directory

---

e2e/logging_metrics_monitoring/logging_metrics_monitoring_test.go
pkg/resources/fluentd/prometheusrules.go

chore: fine-tune FluentdPredictedBufferGrowth

---

charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngclusteroutputs.yaml
charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngoutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_syslogngclusteroutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_syslogngoutputs.yaml
config/crd/bases/logging.banzaicloud.io_syslogngclusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_syslogngoutputs.yaml
docs/configuration/plugins/syslogng-outputs/s3.md
pkg/sdk/logging/model/syslogng/config/output_tests/s3_test.go
pkg/sdk/logging/model/syslogng/output/s3.go

Adds new fields to Axosyslog S3 output.

feat: add new axosyslog s3 fields
