pkg/apis/logging/v1alpha1/loggingplugin_types.go
pkg/controller/plugin/plugin_controller.go
pkg/resources/plugins/configmap.go
pkg/resources/plugins/plugins.go
pkg/resources/reconciler.go
pkg/resources/templates/templates.go
pkg/util/util.go

| Bug fix?        | yes|
| New feature?    | no|
| Deprecations?   | no|
This PR fixes the ability to use multiple plugin crs. Now if multiple plugin crs are submitted the created ConfigMap will hold all cr related config instead of overwriting it.

Allow to add multiple configuration file to configmap

---

deploy/crds/logging_v1alpha1_fluentd_cr.yaml
docs/plugins/elasticsearch.md
pkg/resources/plugins/elasticsearch.go

**Fluentd**
-  'fluentd' version '1.1.2' ->  'fluentd' version '1.4.2'
**Plugins**
- fluent-plugin-s3 1.1.7 -> 1.1.9
- fluent-plugin-rewrite-tag-filter 2.1.1 -> 2.2.0
- fluent-plugin-prometheus 1.2.1 -> 1.3.0
- fluent-plugin-oss 0.0.1 -> 0.0.2
- fluent-plugin-kubernetes_metadata_filter 2.1.5 -> 2.1.6
- fluent-plugin-elasticsearch 2.12.2 -> 3.4.1
**Elasticsearch Plugin**
- ssl_version
- ssl_verify
[more info](https://github.com/uken/fluent-plugin-elasticsearch#user-password-path-scheme-ssl_verify
)

Elasticsearch ssl verify check parameter support

---

docs/plugins/parser.md
pkg/resources/plugins/parser.go

Adds the reserve_data option to the ParserFilter template.
I want to retain Kubernetes (and other) metadata fields from the event for analysis.

Add reserve_data option to ParserFilterTemplate

---

pkg/resources/fluentbit/config.go

| New feature?    |yes
Add extra parameter to fluent-bit configuration.
Without this prefix fluent-bit won't attach Kubernetes metadata to log.

Add Kube_Tag_Prefixparameter for fluent-bit config

---

pkg/resources/fluentd/appconfigmap.go

| Bug fix?        |yes|
| New feature?    |no|
| API breaks?     |no|
| Deprecations?   |no|
This PR fixes the reconcile loop so it will not delete the already configured fluent Configmap if fluentd updated.

Do not remove the generated app-config if fluentd resource updated

---

README.md
docs/examples/es.md
docs/plugins/parser.md
pkg/resources/plugins/parser.go

This PR enables kubernetes metadata forwarding with the fluentd parser plugin by default to send metadata along with the parsed fields.
The fluentd plugin "Kubernetes Metadata Filter" has been removed from the readme to avoid confusion since it's not used and not required for metadata collection and forwarding. Kubernetes metadata is collected and populated into log items in fluent-bit. 
Forwarding Kubernetes metadata should be the default option as it is already collected by fluent-bit. 
In case the parsed log fields overlap with the kubernetes fields, the kubernetes fields will win.

Fix kubernetes metadata forwarding

---

deploy/operator.yaml

Update image tag in operator yaml for those who deploy the operator using the yaml files directly. It's already pointing to the correct one in the helm chart.

update image tag to the latest in operator.yaml

---

docs/plugins/s3.md
pkg/resources/plugins/s3.go

| New feature?    | yes|yes
This adds the ability to specify that path in s3 to send the logs. This preserves the existing path as the default.
You may, in the case of buckets shared with other types of artifacts, want to change exactly where the logs get stored.
Testing:
* Built a docker image with my change
* redeployed logging operator
* Modified `s3-output` helm chart with the configuration
* Pushed a custom logger path
As far as edge cases, if there isn't a trailing `/` at the end of the path, the `path` will not be treated as a directory, but instead a prefix for the file. This appears to be a quirk of …

Add `path` argument to s3 plugin

---

charts/logging-operator/templates/rbac.yaml

| Related tickets |
This fixes the logging operator helm charts, which are currently broken if you enable pod security policies.
If you enable pod security policies, a helm install fails.

v2: Indent psp rbac groups correctly

---

charts/logging-operator-fluent/Chart.yaml
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
deploy/operator.yaml
hack/test.sh

| Related tickets | fixes #133 
- support tls type secret
- support configuring tolerations
this is a final feature release for the current development line which is now considered 1.0.0, but development will continue on version 2 (v2 branch), which will be merged into the master branch soon.

bump image and chart versions to 1.0.0 as the last feature release of the current development line

---

config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_outputs.yaml
docs/plugins/outputs/loki.md
pkg/model/output/loki.go
pkg/model/output/loki_test.go
pkg/model/output/zz_generated.deepcopy.go
pkg/model/types/stringmaps.go

| Related tickets | fixes #211
This PR will separate `labels` and `extra_labels`
Using `labels` is for record_accessor syntax like:
```
labels:
hostname:      hostname //same as $.hostname
|                           |
Loki label name .   Value from record => hostname field 
```
Using `extra_labels`
```
extra_labels:
clustername:      mycluster
|             |
Loki label name .   Value as string
```

Loki Extra labels and Labels fix

---

pkg/resources/fluentd/config.go
pkg/resources/fluentd/configsecret.go

| Related tickets | fixes #240 
Fix an error introduced during adding configurable error level in fluentd.
The error causes the monitoring integration be disfunctional in the default case.
Added proper error handling to the `generateConfig` method.

Fix fluentd config template and error handling #240

---

charts/logging-operator-logging/README.md
config/crd/bases/logging.banzaicloud.io_loggings.yaml
docs/crds.md
go.mod
go.sum
pkg/resources/fluentbit/daemonset.go
pkg/resources/fluentd/statefulset.go
pkg/sdk/api/v1beta1/fluentbit_types.go
pkg/sdk/api/v1beta1/fluentd_types.go

Logging is critical infrastructure, and so users may wish to ensure that
fluentd and/or fluentbit are scheduled before other workloads on nodes. This
is done through exposing `PriorityClassName` in the `fluentd` and `fluentbit`
CRDs.
| New feature?    |yes
This adds support for setting priority classes for fluentd and fluentbit.
Operators may wish to ensure that they get scheduled to nodes before other workloads, and to ensure that they get priority in terms of resources

Add support for Priority Classes for fluentd and fluentbit

---

Makefile
config/crd/bases/logging.banzaicloud.io_loggings.yaml
config/samples/logging_v1alpha2_logging_pvc.yaml
docs/crds.md
pkg/k8sutil/resource.go
pkg/resources/fluentbit/daemonset.go
pkg/resources/fluentbit/fluentbit.go
pkg/resources/fluentd/fluentd.go
pkg/resources/fluentd/service.go
pkg/resources/fluentd/statefulset.go
pkg/sdk/api/v1beta1/logging_types.go

| Related tickets | fixes #249 
Support an for an optional desired state hook to be called before update. It will receive the current state and can alter the desired object if necessary. E.g. service.spec.clusterIP can be set to the current  value to avoid errors when updating with an empty value.
Add support for removing objects if they cannot be updated (similar to how the prometheus operator manages statefulset updates). 
Add and fix some docs.
Fix pvc default config for fluentd.

Manage desired state for resources having limited update capability (statefulset, daemonset)

---

charts/logging-operator-fluent/README.md
charts/logging-operator-fluent/templates/fluentd-cr.yaml
charts/logging-operator-fluent/values.yaml
pkg/apis/logging/v1alpha1/fluentd_types.go
pkg/resources/fluentd/deployment.go

Added a field `deploymentStrategy` to the fluentd CRD, and add support to the helm chart. The field controls the value of `Spec.Strategy` in the fluentd deployment generated by the operator, which defaults to `RollingUpdate`. The current default behaviour is preserved if the new chart value is left unset, i.e. the CRD spec remains the same. If the value is set, e.g. to `Restart`, then the CRD will be updated accordingly and the fluentd deployment's spec will get `Spec.Strategy` equal to `Restart`.
In some providers and storage classes attempting to rollout changes to the fluentd deployment will result …

V1: Permit custom deployment strategy for fluentd

---

charts/logging-operator/templates/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
pkg/sdk/api/v1beta1/fluentd_types.go
pkg/sdk/api/v1beta1/logging_types.go
pkg/sdk/api/v1beta1/zz_generated.deepcopy.go

We use the sdk from banzaicloud/pipeline where we have a 1.13 k8s client that makes it hard to create a Logging CR with default values, since the PersistentVolumeClaimSpec has a field that is pointer but not tagged as omitempty and will fail validations on the newer server versions.
This PR makes it easier to do by making the whole fluentdPvcSpec field omitable.

make fluentdPvcSpec a pointer to make it easier to use with old clients

---

pkg/resources/fluentbit/service.go
pkg/resources/fluentd/service.go
pkg/sdk/api/v1beta1/logging_types.go

| API breaks?     | kinda
| Related tickets |
There are two commits here:
- Only deploy the `ServiceMonitor` when explicitly asked
- Correctly specify the port in the annotations when `PrometheusAnnotations` is set to `true`
Monitoring with Prometheus without using the Prometheus Operator is broken without these changes
Tested on EKS 1.14
There is a potential issue where people relied on the behavior of the `ServiceMonitor` objects being created just by the presence of the `metrics` object in the CRD. However, I decided to leave the current behavior to match what the documentation says. We can switch this, and make it default to `true` …

Fixes for ServiceOperator-less prometheus monitoring

---

docs/crds.md
pkg/sdk/api/v1beta1/logging_types.go

Change the default destination for fluentd internal logs to be the null output.
Because these logs are sent to stdout anyways, so there is no use in sending them to stdout again.

change the fluentd internal log destination to null

---

charts/logging-operator/README.md
charts/logging-operator/templates/deployment.yaml

| New feature?    |yes
Adds annotations for the logging-operator itself in the helm chart
We specifically use this to add annotations for prometheus scraping
Tested on EKS 1.14.
It is possible for our specific use-case could be solved by adding a prometheus-specific toggle, but allowing generic annotations seems to be a better solution.

Allow annotations in logging-operator helm chart

---

charts/logging-operator-logging/README.md
charts/logging-operator/README.md
docs/crds.md
fluentd-image/v1.7/Dockerfile
pkg/sdk/api/v1beta1/logging_types.go

Without allowing access to the /buffers path the configcheck fails for file output configured to write there as it has no pvc mounted.

create and allow the /buffers path for fluent

---

charts/logging-demo/templates/output_elasticsearch.yaml
docs/example-es-nginx.md

Replaces the upmc operator with ECK in the demo docs.
The upmc operator uses an outdated version of elasticsearch and seems to have been unmaintained for several months now.

Update docs to use Elastic Cloud on Kubernetes

---

pkg/sdk/api/v1beta1/logging_types.go

Raise the default memory limit
Because when chunks gets full (256M) then the default 200M memory limit will be exhausted.

raise memory limit to avoid OOM errors when chunks are getting full

---

.circleci/config.yml

helm version upgraded to `2.16.1` in `banzaicloud/helm@0.0.6`

circleci: bump helm orb version to 0.0.6

---

docs/deploy/manifests/deployment.yaml

After much tinkering and trying to figure out why the operater wouldn't work i realized the operater image in the deployment hasn't been updated in quite some time.

Update deployment image to use version 2.7.0

---

charts/logging-operator/Chart.yaml
charts/logging-operator/templates/service.yaml

| Related tickets | fixes #306
This PR fixes the following issue https://github.com/banzaicloud/logging-operator/issues/306
An erroneous label selector was set on the logging-operator service.

[charts/logging-operator] fix service label

---

docs/plugins/outputs/buffer.md
pkg/sdk/model/output/buffer.go

Add an explicit default for the `timekey_wait` buffer parameter.
It is highly confusing that logging-operator specifies "no default" for the `timekey_wait` parameter. This causes fluentd itself to default to `10m` which can be confusingly long both for testing logging-operator and for production environments. While not altering fluentd's defaults, this commit at least makes it explicit and obvious for new users.

Add explicit default for timekey_wait buffer parameter

---

pkg/resources/fluentd/appconfigmap.go
pkg/resources/fluentd/component.go
pkg/resources/fluentd/components.go
pkg/resources/fluentd/configsecret.go
pkg/resources/fluentd/fluentd.go
pkg/resources/fluentd/meta.go
pkg/resources/fluentd/psp.go
pkg/resources/fluentd/rbac.go
pkg/resources/fluentd/service.go
pkg/resources/fluentd/statefulset.go

This pull request adds a `component` label to fluentd pods and service selector.
Without the label, the service considers the pod used to check config as a valid target (as the labels of the pod match the service selector).
With the `component` label, only the pods from the fluentd statefullset match the fluentd service.

Add component label to fluentd pods and service selector

---

docs/quickstarts/es-nginx.md

Troubleshooting guideline link is not rendering properly. This edit fixes link and blockquote.
Issues with  documentation

Fix: link to troubleshooting guideline in docs

---

charts/logging-operator-logging/Chart.yaml
charts/logging-operator-logging/README.md
charts/logging-operator-logging/templates/clusterflows.yaml
charts/logging-operator-logging/templates/clusteroutputs.yaml
charts/logging-operator-logging/values.yaml

Adds the option of deploying ClusterFlow and ClusterOutput objects as part of the logging chart.
Currently to deploy the operator and all our config requires deploying:
1. The operator chart
2. The logging chart to create the logging object
3. A custom chart which contains our cluster-wide configuration
These PR will allow us to drop the custom chart.

Add ClusterFlows/Outputs to logging chart

---

charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/templates/_helpers.tpl
charts/logging-operator/templates/deployment.yaml
charts/logging-operator/templates/psp.yaml
charts/logging-operator/templates/rbac.yaml
charts/logging-operator/templates/service.yaml
charts/logging-operator/values.yaml

| Deprecations?   |yes
This PR adds the ability to manually override the deployment namespace for helm chart installations.
Provide a way to manually override the deployment namespace. This is mainly used by ci-cd tools which dont have the ability to change namespace context.
Some legacy cd tools lack the ability to change namespace context, this feature allows them to manually override the namespace without having that ability.

added helm chart namespace override

---

pkg/sdk/resourcebuilder/component.go

Pin the operator version to avoid accidentally upgrading using the latest tag.

pin the operator version right in the resource builder

---

pkg/sdk/resourcebuilder/component.go

Bump operator version that supports leader election properly
3.0.0 fails when leader election is enabled

bump operator version

---

.circleci/config.yml
scripts/trigger-docs-update.sh

Triggers docs update workflow on `logging-operator-docs` when release tag pushed.

circleci: trigger docs update on release tags

---

pkg/resources/fluentd/statefulset.go

Switch the `config-reloader` to use the `fluentd` [/api/config.gracefulReload](https://docs.fluentd.org/deployment/rpc#api-config-gracefulreload) webhook.
`/api/config.gracefulReload` sends a `SIGUSR2` signal to the fluentd process, instead of `SIGHUP`. This is a more graceful method of reloading the configuration that doesn't require restarting the worker process.
As of v1.9.0, the [fluentd documentation](https://docs.fluentd.org/deployment/signals#sigusr2) recommends using the `SIGUSR2` signal for this purpose.
Sending the `SIGHUP` signal to fluentd and restarting the worker process can …

feat: use fluentd gracefulReload for configuration updates

---

pkg/resources/fluentbit/psp.go

Fix nil exception
```
rvgl  4:00 PM
if enabled fluentbit.security.podSecurityPolicyCreate: true. I got error in logging-operator:
E0520 13:57:43.466474       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 482 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1560d80, 0x2489790)
/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1560d80, 0x2489790)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/banzaicloud/logging-operator/pkg/resources/fluentbit.(*Reconciler).clusterPodSecurityPolicy( …
```

Only add HostPath to PSP if PositionDB enabled

---

charts/logging-operator/Chart.yaml
charts/logging-operator/templates/service.yaml

Do not add the clusterIP with an empty value as it makes helm3 upgrades to fail.

Omit empty clusterIP in the logging service spec to avoid helm3 upgrade failures

---

charts/logging-operator/Chart.yaml
charts/logging-operator/templates/service.yaml
charts/logging-operator/values.yaml

Fix http.service.clusterIP value to mind the scoping and to be backwards compatible with 3.0.5 and earlier chart versions
Charts prior to 3.0.5 (inclusive) used `ClusterIP: None` which was then changed to `ClusterIP: ""` which is bad for two reasons:
- it is backwards incompatible
- it behaves really bad with helm3, which tries to update this value on each upgrade to set it back to the empty string which fails on the API server

Fix helm chart to properly set clusterIP

---

Makefile

| Bug fix?        |yes|
| New feature?    | no|
| Deprecations?   | no|
Remove unused rbac generation controller-gen flag from the first line of make manifests since the second line will handle that.

Remove unused rbac generation flag from make manifests

---

config/crd/kustomization.yaml

Hello. I see two resources, specified in `config/crd/kustomization.yaml` file, but they do not exists by specified path. As well I tried execute `kustomize build` in `config/default`, and it failed also. Can we fix it like that?

Removed not exists resources from crd kustomize template

---

charts/logging-operator-logging/Chart.yaml
charts/logging-operator-logging/templates/logging.yaml

| Related tickets | fixes #540
Modifications to logging.yaml template to fix logging object when it renders without TLS enabled
Running tls.enabled=false produces invalid yaml

fix: logging-operator-logging logging.yaml template

---

charts/logging-operator/Chart.yaml
charts/logging-operator/templates/serviceMonitor.yaml

| Q | A
| Bug fix? | yes
| New feature? | no
| API breaks? | no
| Deprecations? | no
| License | Apache 2.0
Fixing case of `monitoring.serviceMonitor.enable` in the ServiceMonitor manifest
All documentation says that enable is lowercase, while in the chart it is uppercase

Fix logging-operator Helm chart option for monitoring.serviceMonitor.enable

---

fluentd-image/v1.10/healthy.sh

This removes a spurious `-d` flag in the `touch` command in fluentd's liveness check.
When you pass multiple of the same flag to `busybox`, only the last one is used.
```bash
/ # touch /tmp/marker-liveness 
/ # ls -lh /tmp/marker-liveness 
-rw-r--r--    1 root     root           0 Oct 14 14:39 /tmp/marker-liveness
/ # touch -d any -d bullshit -d whatsoever -d @1602683841 /tmp/marker-liveness 
/ # ls -lh /tmp/marker-liveness 
-rw-r--r--    1 root     root           0 Oct 14 13:57 /tmp/marker-liveness
```
Removing it adds clarity and removes confusion.

Remove extra, useless `-d` flag in liveness check

---

fluentd-image/v1.11/healthy.sh

| New feature?    |no
| API breaks?     |no
| Deprecations?   |no
Remove the useless `-d date` in the healthcheck, as was done in the v10 image.
Due to an oversight, I unfortunately did not include this in #539. Sorry about that.

Remove useless `-d date` in fluentd healthcheck

---

charts/logging-operator-logging/README.md
charts/logging-operator/README.md
fluentd-image/v1.11/Dockerfile
pkg/sdk/api/v1beta1/logging_types.go
pkg/sdk/model/output/kinesis_firehose.go
pkg/sdk/model/output/kinesis_stream.go
pkg/sdk/model/output/loki.go

FluentD 1.11.4 -> 1.11.5
Updated plugins:
- fluent-plugin-cloudwatch-logs '0.11.0' -> '0.11.1'
- fluent-plugin-grafana-loki '1.2.15' -> '1.2.16'
- fluent-plugin-kinesis '3.2.3' -> ‘3.3.0'
- fluent-plugin-webhdfs' '1.2.5' -> '1.3.1'
New Plugins:
- fluent-plugin-syslog_rfc5424 '0.9.0.rc.5' 
- fluent-plugin-kubernetes_sumologic '2.4.2'
alpine:3.12 -> '3.12.1'

fluentd:v1.11.5-alpine-1

---

charts/logging-operator/templates/serviceMonitor.yaml
charts/logging-operator/values.yaml

Adds configuration options to serviceMonitor configuration for operator pods
Allows the additional of labels just to the serviceMonitor, so multi tenant prometheus environments can select just the serviceMonitors they're interested in.

Add ServiceMonitor configuration options

---

charts/logging-operator/templates/clusterrolebinding.yaml
charts/logging-operator/templates/psp.yaml
charts/logging-operator/templates/serviceaccount.yaml

See https://github.com/kubernetes/kubernetes/issues/95817
The operator psp didn't work when we upgraded to 1.19.

Fix PSP on k8s 1.19

---

.circleci/config.yml
charts/logging-operator/values.yaml
hack/test.sh

Do not install CRDs from templates.
Switch to assuming helm 3 by default when installing the chart and do not install CRDs as templates, but rely on the crds folder to install them.
Because otherwise helm3 will fail when trying to install crds from templates, since those have already been installed in the beginning from the crds folder.

Assume Helm 3 as the default

---

pkg/resources/fluentd/appconfigmap.go
pkg/resources/fluentd/config.go
pkg/resources/fluentd/configsecret.go
pkg/resources/fluentd/fluentd.go

| Related tickets | fixes #681
Make configcheck identical to production config

Fix configcheck secret to be identical to production config

---

Makefile
charts/logging-operator/templates/deployment.yaml
charts/logging-operator/values.yaml
main.go

Usage from One Eye
```yaml
spec:
logging:
operator:
namespace: default
containerOverrides:
command: ['/manager', '--pprof']
```

Add pprof flag

---

pkg/sdk/resourcebuilder/component.go

Bump image version in SDK to refer to the latest logging operator image.

Bump operator image version

---

.circleci/config.yml

Circle CI Licensei check disabled. Now running under GH Action

Circle CI Licensei check disabled

---

pkg/resources/nodeagent/nodeagent.go

when having default windows tolerations and setting tolerations in the
helm chart, the merge of those arrays don't work as expected.
not all clusters have taints on their windows nodes, in general
`nodeSelector` should work fine.
Removes the tolerations from the windows nodeAgent daemonset to allow users specifying them as needed.
When having predefined tolerations and trying to specify own tolerations the merge of the slice doesn't work as expected. 
E.g. I set the following via helm chart:
```
tolerations:
- operator: Exists
```
To allow for any taint to be tolerated. The merge of the slices then ended up in the …

fix: remove windows tolerations

---

charts/logging-operator/templates/deployment.yaml

| Related tickets | n/a
This change avoids a trailing space in the template.
`yamllint` flags the trailing space as an error.
n/a

Avoid trailing space in template

---

pkg/sdk/resourcebuilder/component.go

Make the disableWebhook field available when serialized.
There are cases where downstream code cannot properly decide whether cert-manager is enabled or not (or simply don't want to use it) and might need to disable webhook creation to skip them, or to manage them separately.

Make the disableWebhook field available when serialized

---

pkg/sdk/model/output/splunk_hec.go

Updates the example in the Splunk docu to be correct.
The field names were wrong and not consistent with the rest of the docu
N/A

[fix] Fields `hec_host` and `hec_port` in splunk example

---

charts/logging-demo/Chart.yaml
charts/logging-operator-logging/Chart.yaml
charts/logging-operator-logging/README.md
charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/values.yaml
fluentd-image/v1.13/Dockerfile
pkg/sdk/api/v1beta1/logging_types.go
pkg/sdk/model/output/elasticsearch.go
pkg/sdk/resourcebuilder/component.go

- fluent-plugin-elasticsearch version rollback 5.1.5 -> 5.0.5
- release version bump 3.14.2

fluent-plugin-elasticsearch opensearch fix

---

charts/logging-operator-logging/README.md
charts/logging-operator/README.md
fluentd-image/v1.13/Dockerfile
pkg/sdk/api/v1beta1/logging_types.go

- fluent-plugin-elasticsearch version rollback 5.1.5 -> 5.0.5
- release version bump 3.14.2

fluent-plugin-elasticsearch opensearch fix (#821)

---

pkg/resources/fluentd/prometheusrules.go

Label Fluentd alerts with their rule group name. Also, make sure all Fluentd alerts have at least `namespace` and `pod` labels.
Make it easier to filter `ALERTS` metrics.

Fluentd alert enhancements

---

go.mod
main.go
pkg/sdk/model/types/builder.go

| Related tickets | partially fixes #825 
Add default_metrics_labels for the default route with the flow id.
Because right now the default flow id is not available in the metrics when metrics is enabled for fluentd. Along with https://github.com/banzaicloud/fluent-plugin-label-router/issues/16 it actually fails and unable to process messages.

Default metrics labels

---

pkg/sdk/resourcebuilder/component.go

Tag `EnabledComponent` as *inline* for controller-gen.
Without the tag controller-gen will fail to process `ComponentConfig`. This problem doesn't surface in this codebase but third-party users of the pkg/sdk might run into this.

tag EnabledComponent as inline for controller-gen

---

pkg/resources/fluentd/rbac.go

| Related tickets | fixes #862 
Simply adds the pods resource to the FluentD cluster role
The enhanceK8s filter plugin requires this access

Add pods to fluentd cluster role

---

pkg/resources/fluentd/rbac.go

This removes the Extensions API from the ClusterRole for Fluentd.  This was used for Deployments permissions
The deployments extensions API has been removed from k8s as of v1.16.  It should no longer be required.
- [ x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)

Remove extensions API

---

pkg/resources/fluentbit/config.go
pkg/resources/fluentbit/configsecret.go
pkg/resources/nodeagent/config.go
pkg/resources/nodeagent/configsecret.go

| Related tickets | fixes #888 
Change the way fluentbit configuration is generated when multiline.parser field is used.
Currently the operator generates an invalid configuration for fluentbit when multiline.parser field is used.
There are two problems with the generated configuration:
- A typo (an extra `:` char)
- An extra statement `Parser crio` in the INPUT section of the configuration. Because Parser field has a default value based on the contianer runtime environment, it is always rendered in the configuration.
The multiline.parser documentation (see https://docs.fluentbit.io/manual/pipeline/inputs/tail#multiline-cor …

Fix fluentbit multiline

---

pkg/sdk/logging/api/v1beta1/logging_types.go

Move default fluentd sidecar images to external global variables
So it ease readability of the current supported images for a given version of logging operator

chore: move default images repositories and tags to globals

---

config/dashboards/logging-dashboard.json

Update the dashboard to use the replacement for kube-state-metrics deprecated metrics.
These metrics where removed several releases ago which makes the dashboard show N/A values.
See https://github.com/kubernetes/kube-state-metrics/tree/release-1.9/docs#metrics-deprecation

fix(dashboard): update to latest kube_pod_container_resource metrics

---

charts/logging-operator-logging/templates/eventtailer.yaml
charts/logging-operator-logging/templates/hosttailer.yaml
charts/logging-operator-logging/values.yaml
config/samples/extensions/logging-extensions_v1alpha1_hosttailer.yaml

helm chart templates for logging extensions resources: eventtailer, hosttailer
to make helm chart users to be able to configure the resources through values.yaml
handle the changes made in https://github.com/banzaicloud/logging-operator/pull/936

hosttailer, eventtailer charts

---

controllers/logging/logging_controller.go

| Related tickets | related https://github.com/banzaicloud/logging-operator/issues/918
Set RecreateErrorMessageCondition to MatchImmutableErrorMessages
Statefulset immutable errors should be detected.
This PR may be optional if https://github.com/banzaicloud/operator-tools/pull/103 is merged.

Match statefulset immutable errors

---

pkg/resources/nodeagent/configsecret.go
pkg/resources/nodeagent/nodeagent.go

| Related tickets | fixed #920 
Add nil pointer checker around `nodeAgentInstance.fluentdDataProvider` and make sure it's passed in when nodeInstanceAgent is created. Stems from using it here: https://github.com/banzaicloud/logging-operator/blob/master/pkg/resources/nodeagent/configsecret.go#L237 and it never being set here: https://github.com/banzaicloud/logging-operator/blob/master/pkg/resources/nodeagent/nodeagent.go#L319-L323
causing a panic when trying to access a nil pointer
when the instance was setup it was forgotten to pass the main reconcile fluentDataProvider down to the subsequent reconcilers. The only one …

Fix Nil Pointer Panic around configsecret Reconciler

---

e2e/common/setup/loggingoperator.go
pkg/sdk/resourcebuilder/component.go

fixes disableWebhook option of resourcebuilder to remove webhook settings and mutatingwebhookconfigurations on a reconcile loop when disableWebhook flag set
worked only on first run

disableWebhook fix: now also removes mutatingwebhookconfigurations

---

pkg/resources/fluentbit/daemonset.go
pkg/resources/fluentbit/meta.go
pkg/resources/fluentd/meta.go
pkg/resources/fluentd/statefulset.go

| Related tickets | fixes #959, closes #960 
Fix #959 by returning a deep copy of the object metadata assembled by `FluentdObjectMeta` and `FluentbitObjectMeta`.
Also, stop adding `statefulsetAnnotations` and `daemonsetAnnotations` to resources other than the Fluentd statefulset and Fluentbit daemonset.
Adding the annotation maps from the config in e3b340132bc4658271c8934e13e1c8a5a1ae6cc6 to the object metadata caused sharing between resources which resulted in action-at-a-distance.

Fix statefulset recreate loop

---

charts/logging-operator/Chart.yaml
charts/logging-operator/README.md
charts/logging-operator/templates/serviceaccount.yaml
charts/logging-operator/values.yaml

Add `annotations` for logging-operator `ServiceAccount`
Custom annotations are needed for ServiceAccount

feat: Add annotations for logging-operator ServiceAccount

---

pkg/resources/fluentd/statefulset.go

| Related tickets | fixes https://github.com/banzaicloud/logging-operator/issues/966
Changes the buffer volume name in the STS definition to use the qualified name

fix: default fluentd bufferStorageVolume is not well referenced

---

drain-watch-image/drain-watch.sh
e2e/common/cluster.go
e2e/volumedrain/volumedrain_test.go
pkg/resources/fluentd/statefulset.go
pkg/sdk/logging/api/v1beta1/logging_types.go

| Related tickets | fixes #952 
Custom runner env for drainer job's node exporter. This way the drain-watch.sh is able to shut down the container with a simple http call.
Drainer job's node exporter didn't finish originally.

Node exporter custom runner for drainer job

---

charts/logging-operator-logging/templates/eventtailer.yaml
charts/logging-operator-logging/templates/hosttailer.yaml

This allows eventTailer and hostTailer container defaults to be overridden when using the logging-operator-logging chart values.yaml. 
This is useful for overriding images for these pods for instance when running in an air gapped 
environment.

Allow containerOverrides for eventtailer and hosttailer to be set from logging-operator-logging values.

---

charts/logging-operator-logging/templates/eventtailer.yaml
charts/logging-operator-logging/values.yaml

Add the storageClass option to specify the PVC provisionner in the EventTailer chart entry.
This allows theuse of a non default storage class.

feat: add storageclass to eventtailer chart

---

pkg/sdk/logging/model/output/elasticsearch.go
pkg/sdk/logging/model/output/elasticsearch_test.go

Making the Elasticsarch's output attribute `data_stream_enable` hidden to make sure it is not rendered into the Fluentd configuration file.
Attribute `data_stream_enable` is artificial / only used by the logging operator. It is not something Fluentd knows about as the data stream usage is denoted by different `@type` (`elasticsearch_data_stream` vs `elasticsearch`).
The extra attribute does not really break anything, but Fluentd prints ugly warning for each output using data stream.
```
2022-07-29 13:14:35 +0000 [warn]: parameter 'data_stream_enable' in <match **>
@type elasticsearch_data_stream
@id ...
data_stream_enable …
```

Fix Fluentd warning "parameter 'data_stream_enable' is not used"

---

pkg/sdk/logging/model/output/elasticsearch_test.go

| Bug fix?        | yes (bug in test)
Simple fix for a failing test. Probably caused by a merge of https://github.com/banzaicloud/logging-operator/commit/20a3f939ae9d95d01c4fb75cf2444089d1a6935c.

Fix failing TestElasticSearchDataStream

---

.github/workflows/node-exporter-image.yml
node-exporter-image/Dockerfile
node-exporter-image/buffer-size.sh
pkg/resources/fluentbit/daemonset.go
pkg/sdk/logging/api/v1beta1/logging_types.go

Node exporter's custom-runner powered image build moved into logging-operator repo
Using the new multiple exec feature of custom-runner to run multiple processes at startup (node exporter, buffer-size.sh)

Node exporter update master

---

pkg/resources/fluentd/prometheusrules.go

| Related tickets | see https://community-banzaicloud.slack.com/archives/CGMPPBZBK/p1666622764104409
Updates FluentdPredictedBufferGrowth alert
The current alert triggers in a non consistent manner.

fix: update FluentdPredictedBufferGrowth alert

---

pkg/resources/model/system.go

| Related tickets | fixes #615
Flows in error (referencing non existing output for example) should be skipped when building routing configuration.
Currently, errored flows are kept in the fluentd config, which makes the configcheck fails and the world stops until the source resources are fixed.
This causes noisy neighborhood issues in a multi-tenant world where users control their flow/output and admins manages the logging infra.

fix: skip errored flows when building the routes

---

charts/logging-operator/templates/psp.yaml

| Related tickets | Closes #1077 
This PR adds a check for the PodSecurityPolicy API in the chart, and avoids trying to use that API if it is not available. This API is [removed in k8s v1.25](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#psp-v125).
I tested this in k8s v1.22 where the PSP is still installed, and in v1.25 where the PSP is not installed anymore. This makes the chart usable in k8s v1.25+.

fix: only install PodSecurityPolicy if the API is available

---

.github/workflows/docker.yml
.github/workflows/docker_fluentd.yml
.github/workflows/drain_watch_image.yml
.github/workflows/helm.yml
.github/workflows/node-exporter-image.yml
.github/workflows/trigger-submodule-update.yml

| Q               | A      |
| --------------- | ------ |
| Bug fix?        | no|
| New feature?    | no |
| API breaks?     | no |
| Deprecations?   | no |
| Related tickets | - |
| License         | Apache 2.0 |
Replaced `::set-output` with `>> $GITHUB_OUTPUT`
Deprecated, will be removed in 2023-05-31.
Details: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.
Tested [in another PR](https://github.com/banzaicloud/koperator/pull/906/files#diff-dce4cd1ca1dc3e5849de0fd3f3c7b132ad537e4ba79ba191f5de4330484b214bR39), worked well.
- ~Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)~
- ~Logging code meets the guideline~
- ~User guide and …

Replaced GHA `set-output` with `GITHUB_OUTPUT`

---

pkg/resources/syslogng/statefulset.go

Syslog-ng stores persist information (like buffer file path) in a persist file. In the case this file is not persisted Pod restart may spawn new buffer files and ignore old files. To prevent this we moved the persist file next to the buffers.

Move persist file next to buffers

---

pkg/k8sutil/cache.go

| Related tickets | fixes #881
Handle flush error in cached RESTMapper constructor.

handle flush error in cached RESTMapper constructor

---

controllers/logging/logging_controller.go
pkg/resources/configcheck/configcheck.go
pkg/resources/fluentd/appconfigmap.go
pkg/resources/fluentd/fluentd.go
pkg/resources/syslogng/configcheck.go
pkg/resources/syslogng/syslogng.go

The PR applies a new logic for cleaning up configcheck resources (secrets and the pod) so that it should be more robust. 
The previous logic was leveraging the config hashes registered in the logging operator status, which could potentially miss obsolete configcheck resources if the hash was not added to the status properly (or was removed prematurely).
The current logic adds a label to each resource and removes all the resources that are not relevant anymore based on the value of the label.
Additionally we make sure that fluentd and syslogng are not configured simultaneously because the two reconcilers would fight for the single `configCheckResults` field in the logging resource status.

Label based configcheck cleanup

---

pkg/resources/kubetool/utils.go
pkg/resources/syslogng/statefulset.go

This fixes an issue when persist file creation fails because there is no `/buffers` directory in the syslog-ng statefulset's syslog-ng container.
The new logic removes the hard coded `--persist-file` flag from syslog-ng's args and only adds it if it finds a volume mount "for buffers".

replace fixed syslog-ng persist file flag with guessed dynamic

---

config/samples/logging_v1alpha2_logging_debug.yaml
pkg/resources/nodeagent/nodeagent.go
pkg/sdk/extensions/extensionsconfig/config.go
pkg/sdk/logging/api/v1beta1/logging_types.go

the current version has Critical CVEs ...
updating fluent-bit to 1.9.10 newest patchlevel.
there is also 2.0.9 landed already

fix: update fluent-bit

---

renovate.json

- disable major upgrades by default
- disable golang.org/x/exp package
- use consistent k8s version for client-go

chore: renovate tuning

---

docs/configuration/crds/v1beta1/logging_types.md
e2e/charts/logging-operator-logging/Chart.yaml
e2e/charts/logging-operator-logging/templates/logging.yaml
e2e/charts/logging-operator-logging/values.yaml
pkg/sdk/logging/api/v1beta1/logging_types.go

add support for syslogNG and errorOutputRef
some cleanups:
- replace `if` with `with`
- replace `indent` to `nindent` (and nicer indent)
- reorder like in docs / crd-struct (and take comments from crd-struct to helm-chart)

fix(e2e/charts): add logging-operator-logging syslogNG + errorOutputRef support

---

pkg/resources/fluentbit/config.go
pkg/resources/fluentbit/configsecret.go
pkg/resources/fluentbit/daemonset.go

fix: do not refer to upstream config item to avoid hiding fluentbit configuration, also use absolute path in the config

---

pkg/resources/fluentd/fluentd.go

If prometheus crd are available, resourceObjects get lost for reconciling. In effect no Statefulset for fluentd will created.
solved: https://github.com/kube-logging/logging-operator/issues/1384

fix append slice

---

pkg/resources/fluentbit/configsecret.go
pkg/resources/nodeagent/configsecret.go
pkg/resources/nodeagent/nodeagent.go
pkg/sdk/logging/api/v1beta1/fluentbit_types.go

This means that pods with specific exclude annotations will be omitted from log collection, see https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#kubernetes-annotations
Note: this is a possible breaking change, although the chance to be affected by this should be close to zero.

fluentbit: enable annotation based exclude by default (fluentbit.io/exclude: true)

---

controllers/logging/logging_controller.go
controllers/logging/logging_controller_test.go
pkg/resources/model/repository.go

- Make `logging.spec.watchNamespaces` (explicit static list) and `logging.spec.watchNamespaceSelector` (label based dynamic list) additive instead of exclusive for hopefully better semantics.
- Add tests for better coverage (looking into reusing the same thing for a different use case as well)
- Add namespace watches and trigger reconcile on loggings with watchNamespaceSelector defined

watchNamespaces improvements

---

charts/logging-operator/templates/logging.yaml

helm templating fails with
```
Error: template: logging-operator/templates/logging.yaml:23:22: executing "logging-operator/templates/logging.yaml" at <.Values.logging.fluentd>: fluentd is not a method but has arguments Use --debug flag to render out invalid YAML
```
when `fluentd` value is set.

helm: fix fluentd reference

---

config/samples/logging_logging_with_monitoring.yaml

add example to use monitoring

---

pkg/resources/fluentbit/configsecret.go
pkg/sdk/logging/model/syslogng/config/config.go
pkg/sdk/logging/model/syslogng/config/config_test.go
pkg/sdk/logging/model/syslogng/config/flow.go
pkg/sdk/logging/model/syslogng/config/flow_test.go
pkg/sdk/logging/model/syslogng/config/go.mod

- fix: lookup actual cluster output namespace, validate and bail out if invalid
- fix: make cluster.local domain configurable for fluentbit in syslog-ng aggregator mode as well

syslog-ng aggregator fixes

---

pkg/resources/syslogng/syslogng.go
pkg/sdk/logging/api/v1beta1/logging_types.go

Bump node-exporter image to https://github.com/kube-logging/node-exporter-image/releases/tag/v0.7.1
Before
```
node_buffer_size_bytes{entity="/buffers"} 1.7847494e+07
node_buffer_size_bytes{entity="/buffers/lost+found"} 16384
node_buffer_size_bytes{entity="/buffers/tail.0"} 1.7827014e+07
node_buffer_size_bytes{entity="/buffers/tail.0/1-1691495292.546730320.flb"} 1.150976e+06
node_buffer_size_bytes{entity="/buffers/tail.0/1-1691495292.550201690.flb"} 1.773568e+06
node_buffer_size_bytes{entity="/buffers/tail.0/1-1691495292.555055389.flb"} 1.871872e+06
node_buffer_size_bytes{entity="/buffers/tail.0/1-1691495292.564564982.flb"} 1.675264e+06
node_buffer_size_bytes{entity="/buffers/tail.0/1-1691495292.571656826.flb"} 2.073798e+06
node_buffer_size_bytes{entity="/buffers/tail.0/1-1691495292.578683 …
```

deps: update node-exporter image version to v0.7.1

---

Makefile
e2e/fluentd-aggregator/fluentd_aggregator_test.go
pkg/resources/fluentd/config.go
pkg/resources/fluentd/configsecret.go
pkg/resources/fluentd/service.go
pkg/sdk/logging/api/v1beta1/logging_types.go

Select `/aggregated_metrics` Fluentd metrics endpoint by default when multi worker is enabled.
Add E2E test that checks if multi worker is enabled and the two workers correctly get logs.
Tested:
- explicitly setting metrics.path to `/metrics` changes servicemonitor and prom annotation to point to `/metrics` independently of the worker count
- if metrics.path is not set and workers = 1, servicemonitor and prom annotations point to `/metrics`
- if metrics.path is not set and workers > 1, servicemonitor and prom annotations point to `/aggregated_metrics`
Fixes #1110

fix(fluentd): use aggregated metrics with multi workers

---

pkg/resources/syslogng/statefulset.go
pkg/sdk/logging/api/v1beta1/logging_types.go

- Send fluentd output to stdout by default.
- Exclude fluentd logs from ingestion by default.
- Exclude syslog-ng logs from ingestion  by default.
Fixes #1076

feat: exclude aggregators logs from fluentbit 

---

pkg/resources/fluentd/appconfigmap.go
pkg/resources/fluentd/fluentd.go
pkg/resources/syslogng/syslogng.go

This should help us in a situation where the configcheck pod failed, but we expect to succeed the second time (with the same hash).
This might sound suprising first, but to be able to leverage other configcheck strategies like https://github.com/kube-logging/logging-operator/pull/1407 this is going to be useful.

fix: rerun failed configcheck if there is no configcheck pod

---

pkg/resources/fluentd/drainjob.go
pkg/resources/fluentd/fluentd.go

The check interval in the image is 60 (seconds), this can make the draining process significantly faster.

chore: reduce fluentd drainer check interval

---

charts/logging-operator/README.md
charts/logging-operator/templates/logging.yaml
charts/logging-operator/values.yaml

This key is in the [docs](https://kube-logging.dev/docs/logging-infrastructure/logging/#filter-namespaces) but not in the chart

fix(helm): add watchNamespaceSelector key to chart

---

e2e/syslog-ng-aggregator/syslog_ng_aggregator_test.go
pkg/resources/fluentd/statefulset.go
pkg/resources/syslogng/statefulset.go

- Enable buffer volume metrics buffer-size.sh custom metrics retrieval to ease access to buffer size and file count.
- Update syslog-ng e2e tests to configure an emptydir buffer volume and enable buffer metrics
Depends on https://github.com/kube-logging/logging-operator/pull/1423

feat(aggregators): enable bufferVolumeMetrics custom metrics

---

pkg/resources/fluentd/appconfigmap.go
pkg/resources/syslogng/configcheck.go

This PR aims to delay the configcheck pod creation until secrets are available.
Fixes #1406.

fix(configcheck): wait for secrets to be available

---

Makefile
config/samples/mulitenant-hard/README.md

Rename the `generate` makefile rule to `codegen`
Add a new `generate` rule that runs `codegen fmt manifests docs helm-docs`
`check-diff` rule now calls `generate`

chore: global generate makefile rule

---

.github/workflows/artifacts.yaml
Dockerfile

~In PR https://github.com/kube-logging/logging-operator/pull/1506 the OCI labels should have been just after the last `FROM` command, because currently it shows 0 labels.~
~I am not sure why the added tags are not seen on ghcr.io, will test this version and get back to you whether it is shown or not.~
EDIT: Checked the labels added by GHA `meta` step and added some values. Also fixed the missing description on ghcr.io.
See my fork's page: https://github.com/overorion/logging-operator/pkgs/container/logging-operator/134955502?tag=4.4.2
The problem was in fact the multi-arch image, the docs were really helpful:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#adding-a-description-to-multi-arch-images

GHA: fix OCI description, add extra OCI labels

---

go.work.sum
pkg/resources/fluentd/drainjob.go
pkg/resources/fluentd/statefulset.go

Fluentd expects the `/tmp` directory to be writable even if the root file system is mounted as read only. This PR adds a writeable empty dir volume to the fluentd container mounted as `/tmp` as a workaround.
For more details see the linked issue.
fix: #1517

Support read only root file system use case in fluentd

---

controllers/logging/logging_controller.go
pkg/resources/model/reconciler.go
pkg/resources/model/repository.go
pkg/resources/model/resources.go

Usability updates to highlight certain issues in the logging resource status:
- deprecated embedded fluentbit config is used together with logging routes
- watchNamespaceSelector doesn't resolve to actual namespaces
#1495

Updates in logging status problems for usability

---

main.go

The endpoint was tested before the server has started, resulting a failure to start.

main.go: fix --pprof flag

---

pkg/resources/model/reconciler.go

If the original object contains a pointer, then without this patch that pointer will (inadvertently) change.
This is required for the detached fluentd use case.

fix(reconciler): make sure to not update the original object

---

controllers/logging/loggingroute_controller.go
pkg/resources/fluentbit/tenants.go

- fix: notify loggingroute on logging status change
- chore: remove duplicate sort
fixes [#1638](https://github.com/kube-logging/logging-operator/issues/1638)

Fix loggingroute notifications for changes in the logging resource status

---

pkg/resources/nodeagent/config.go

both linux and windows have it at the same location
Looking at that, I wonder why there are two different specs/types for the same thing (FluentbitSpec and NodeAgentFluentbit) - the former permits to override the config while the latter doesn't.

fix: default parsers conf location wrong on windows

---

charts/logging-operator/templates/logging_eventtailer.yaml
charts/logging-operator/values.yaml

This is a supplement to #1510.
The `EventTailer` spec allows for overriding the image, but that options was not available through the helm chart. 
Here I add that option.

helm: allow eventtailer image override through chart

---

charts/logging-operator/crds/logging.banzaicloud.io_fluentbitagents.yaml
charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
charts/logging-operator/crds/logging.banzaicloud.io_nodeagents.yaml
config/crd/bases/logging.banzaicloud.io_fluentbitagents.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_nodeagents.yaml
docs/configuration/crds/v1beta1/fluentbit_types.md
pkg/sdk/logging/api/v1beta1/fluentbit_types.go

Add support for [`storage.delete_irrecoverable_chunks` option](https://docs.fluentbit.io/manual/administration/buffering-and-storage#service-section-configuration) for Fluentbit

feat(fluentbit): add storage.delete_irrecoverable_chunks option

---

charts/logging-operator/templates/clusterrole.yaml
config/rbac/role.yaml
config/samples/fluentdconfig.yaml
controllers/logging/logging_controller.go
controllers/logging/logging_controller_test.go
main.go
pkg/resources/fluentbit/configsecret.go
pkg/resources/fluentbit/tenants.go
pkg/resources/fluentd/dataprovider.go
pkg/resources/fluentd/fluentd.go
pkg/resources/fluentd/meta.go
pkg/resources/model/reconciler.go
pkg/resources/model/resources.go
pkg/resources/model/system.go
pkg/resources/syslogng/dataprovider.go
pkg/resources/syslogng/meta.go
pkg/resources/syslogng/statefulset.go
pkg/resources/syslogng/syslogng.go
pkg/sdk/logging/api/v1beta1/logging_types.go

This PR aims to fix two problems:
- deleting a fluentdconfig/syslogngconfig resource should also delete the child resources (solved by changing the ownerreferences)
- deleting a logging resource should not be possible until a fluentdconfig/syslogngconfig resource exists. we don't delete the fluentdconfig/syslogngconfig forcefully because those are created by the user, but we can protect against this by using a finalizer. we send an event to the logging object for the user to be able to see other than looking at the operator logs
Fixes #1667.
Signed-off-by: Szilard Parrag <szilard.parrag@axoflow.com>

Fix fluentdconfig and syslogngconfig deletion

---

pkg/resources/fluentd/fluentd.go
pkg/resources/syslogng/syslogng.go

Otherwise it halts all other events for the same object from being reconciled until the specified time
note: the rate limiter will protect us anyways

fix: remove requeue after

---

config/samples/multitenant-routing/logging/tenant-infra-logging.yaml
docs/fluentbit-flow-control.md
pkg/resources/fluentbit/config.go
pkg/resources/fluentbit/configsecret.go
pkg/resources/fluentbit/tenants.go

The consequences of a faulty output can effect other tenants if backpressure kicks in. To avoid this problem we separate inputs from each other by creating a dedicated tail input for each tenant.

Isolate input sources to avoid backpressure affecting other tenants

---

config/samples/multitenant-routing/logging/tenant-infra-logging.yaml
docs/fluentbit-flow-control.md
pkg/resources/fluentbit/config.go
pkg/resources/fluentbit/configsecret.go
pkg/resources/fluentbit/tenants.go

This is a backport of the original [PR](https://github.com/kube-logging/logging-operator/pull/1682) for the release branch

isolate input sources using fixed hash tag and backpressure

---

charts/logging-operator/crds/logging.banzaicloud.io_fluentbitagents.yaml
charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
charts/logging-operator/crds/logging.banzaicloud.io_nodeagents.yaml
config/crd/bases/logging.banzaicloud.io_fluentbitagents.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_nodeagents.yaml
docs/configuration/crds/v1beta1/fluentbit_types.md
pkg/sdk/logging/api/v1beta1/fluentbit_types.go

This PR adds new fields for the [new fluent-bit kubernetes filter options](https://github.com/fluent/fluent-bit/pull/8279/) to allow for enriching logs with kubernetes namespace labels and annotations right at the source
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
name: namespace-label-test
spec:
filterKubernetes:
namespace_annotations: "On"
namespace_labels: "On"
image:
repository: ghcr.io/fluent/fluent-bit/unstable
tag: latest
```

feat: kubernetes namespace labels and annotations with fluent-bit 3.0

---

controllers/logging/logging_controller_test.go
pkg/resources/model/reconciler.go
pkg/resources/model/reconciler_test.go

make the conflict warning smarter and more informative
fixes #1666

chore: remove obsolete deprecation warning from logging status

---

docs/configuration/plugins/outputs/vmware_log_intelligence.md
pkg/sdk/logging/model/output/vmware_log_intelligence.go

- Internal type in vmware log intelligence plugin shouldn't be exposed or be included in docs

doc: Remove internal type

---

docs/scaling.md

Docs needed to be updated to reflect that it's now totally possible to use an HPA directly for the fluentd/syslog-ng statefulset.

chore(docs): update scaling notes

---

charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_outputs.yaml
docs/configuration/plugins/outputs/elasticsearch.md
pkg/sdk/logging/model/output/elasticsearch.go
pkg/sdk/logging/model/output/elasticsearch_test.go

Adds support for configuring compression level in Elasticsearch output.

elasticsearch output compression_level option

---

config/samples/multitenant-routing/logging/tenant-infra-logging.yaml
pkg/sdk/extensions/extensionsconfig/config.go
pkg/sdk/logging/api/v1beta1/logging_types.go

Upgrade [fluentbit to v2.2.2](https://github.com/fluent/fluent-bit/releases/tag/v2.2.2)
Includes https://github.com/fluent/fluent-bit/pull/8129

deps: upgrade fluentbit to 2.2.2

---

pkg/resources/fluentd/appconfigmap.go

Fixes https://github.com/kube-logging/logging-operator/issues/1557

add missing dnsconfig to configcheck pods as well

---

charts/logging-operator/crds/logging.banzaicloud.io_fluentdconfigs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_fluentdconfigs.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
config/samples/archive/logging_v1alpha2_logging_debug.yaml
docs/configuration/crds/v1beta1/fluentd_types.md
pkg/resources/fluentd/config.go
pkg/resources/fluentd/configsecret.go
pkg/sdk/logging/api/v1beta1/fluentd_types.go

This change adds a feature to set FluentD output to json format.
```
spec:
fluentd:
logFormat: json
```
The default is still text. Adding the new value logFormat: json will modify the fluendtd-Container file /fluentd/etc/input.conf.

Feat: add json format for fluentd output

---

docs/configuration/plugins/outputs/buffer.md
pkg/sdk/logging/model/output/aws_elasticsearch_test.go
pkg/sdk/logging/model/output/azurestore_test.go
pkg/sdk/logging/model/output/buffer.go
pkg/sdk/logging/model/output/cloudwatch_test.go
pkg/sdk/logging/model/output/datadog_test.go
pkg/sdk/logging/model/output/elasticsearch_test.go
pkg/sdk/logging/model/output/file_test.go
pkg/sdk/logging/model/output/format_test.go
pkg/sdk/logging/model/output/gcs_test.go
pkg/sdk/logging/model/output/http_test.go
pkg/sdk/logging/model/output/kafka_test.go
pkg/sdk/logging/model/output/kinesis_firehose_test.go
pkg/sdk/logging/model/output/kinesis_stream_test.go
pkg/sdk/logging/model/output/logdna_test.go
pkg/sdk/logging/model/output/loki_test.go
pkg/sdk/logging/model/output/newrelic_test.go
pkg/sdk/logging/model/output/opensearch_test.go
pkg/sdk/logging/model/output/oss_test.go
pkg/sdk/logging/model/output/redis_test.go
pkg/sdk/logging/model/output/s3_test.go
pkg/sdk/logging/model/output/splunk_hec_test.go
pkg/sdk/logging/model/output/sqs_test.go
pkg/sdk/logging/model/output/sumologic_test.go
pkg/sdk/logging/model/output/syslog_test.go
pkg/sdk/logging/model/output/vmware_log_intelligence_test.go
pkg/sdk/logging/model/output/vmware_loginsight_test.go
pkg/sdk/logging/model/render/fluent_test.go

We are changing the default value which had already been updated to a much saner default in fluentd to avoid creating an extensive number of small buffer chunks.
This isn't an intrusive breaking change, but should be highlighted in the release notes in case someone depended on this intentionally or accidentally.
Fixes #1099.

chore(fluentd): do not override fluentd's default buffer size

---

charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
controllers/logging/logging_controller_test.go
docs/configuration/crds/v1beta1/clusteroutput_types.md
pkg/resources/model/reconciler.go
pkg/resources/model/system.go
pkg/sdk/logging/api/v1beta1/clusteroutput_types.go

Protected output flag for ClusterOutputs to disable references from namespaced flows. Docs will need to be updated.
fixes #1709

feat: protected clusteroutput for fluentd

---

charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_outputs.yaml
docs/configuration/plugins/outputs/forward.md
pkg/sdk/logging/model/output/forward.go
pkg/sdk/logging/model/output/forward_test.go

This PR adds support for the time_as_integer configuration parameter to the Forward Output. 
It inclused the addition of a simple test case for the Forward Output.
As specified in the fluentd 0.14 release notes ( https://www.fluentd.org/blog/fluentd-v0.14.0-has-been-released ), when this parameter is set to "true", the events are forwarded formatting the event time as an epoch integer, using second resolution. 
If false, which is the default value, the events are sent as binary data with nanosecond resolution, which crashes old Fluentd versions. 
In some occurrences, this settings can also be useful to forward events to Logstash instances,
because Logstash' "fluent" codec by default is not compatible with the nanosecond resolution binary data that comes from Fluentd.

Forward output time_as_integer

---

charts/logging-operator/crds/logging.banzaicloud.io_fluentbitagents.yaml
charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
charts/logging-operator/crds/logging.banzaicloud.io_nodeagents.yaml
config/crd/bases/logging.banzaicloud.io_fluentbitagents.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_nodeagents.yaml
config/samples/syslog-ng-simple.yaml
docs/configuration/crds/v1beta1/fluentbit_types.md
pkg/resources/fluentbit/config.go
pkg/resources/fluentbit/configsecret.go
pkg/sdk/logging/api/v1beta1/fluentbit_types.go

Add support for [max_worker_connections](https://docs.fluentbit.io/manual/administration/networking#:~:text=2000-,net.max_worker_connections,-Set%20maximum%20number) to limit the number of connections against an aggregator endpoint. Should be used together with workers, which is 2 by default according to [fluentbit docs](https://docs.fluentbit.io/manual/pipeline/outputs/tcp-and-tls#:~:text=double-,Workers,-Enables%20dedicated%20thread).
```
kind: FluentbitAgent
spec:
network:
maxWorkerConnections: 1
syslogng_output:
Workers: 1
```

fluentbit: net.max_worker_connections

---

config/samples/syslog-ng-custom-metrics.yaml
pkg/sdk/logging/model/syslogng/config/config_test.go
pkg/sdk/logging/model/syslogng/config/flow.go
pkg/sdk/logging/model/syslogng/config/log.go

This PR adds flexibility in what label keys should be used automatically for output metrics, also adds the ability to use go templates that receives the destination information (name, namespace, scope:local/global and the logging name) to be used as needed. Example:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: SyslogNGClusterFlow
metadata:
name: all
spec:
match: {}
outputMetrics:
- key: custom_output
labels:
flow: all
my-key-for-the-output: "{{ .Destination.Name }}"
output_name: ""
globalOutputRefs:
- http
```

syslogng: render go templates in metrics-probe label values

---

pkg/resources/fluentd/config.go

see  https://docs.fluentd.org/deployment/system-config#less-than-log-greater-than-section

fix: added missing log section inside system config

---

config/samples/multitenant-routing-2/logging/tenant-infra-logging.yaml
config/samples/syslog-ng-simple.yaml
docs/logging-route.md

By separating inputs for the different tenants, hacking with the workers configuration is now obsolete.

Remove obsolete config samples for multitenant workers

---

pkg/resources/fluentbit/daemonset.go

- Send whole fluentbit SecurityContext to fluentbit, configReloader and bufferVolumeMetrics containers

fix: direct map of fluentbit securitycontext options

---

controllers/logging/logging_controller.go
docs/configuration/crds/v1beta1/fluentbit_types.md
docs/configuration/crds/v1beta1/loggingroute_types.md
docs/logging-route.md
docs/multi-tenancy.md
main.go
pkg/resources/fluentbit/configsecret.go
pkg/resources/model/repository.go
pkg/sdk/logging/api/v1beta1/fluentbit_types.go
pkg/sdk/logging/api/v1beta1/loggingroute_types.go

Keep meaningful warnings, but show them only once to avoid redundant log messages

Cleanup warnings

---

charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_outputs.yaml
docs/configuration/plugins/outputs/gelf.md
docs/configuration/plugins/outputs/kafka.md
e2e/common/helpers.go
e2e/fluentd-aggregator-namespacelabel/fluentd_aggregator_test.go
e2e/fluentd-aggregator/fluentd_aggregator_test.go
e2e/volumedrain/volumedrain_test.go
pkg/sdk/logging/api/v1beta1/logging_types.go
pkg/sdk/logging/model/output/gelf.go
pkg/sdk/logging/model/output/kafka.go
pkg/sdk/logging/model/output/kafka_test.go
pkg/sdk/logging/model/output/zz_generated.deepcopy.go

fix:  #1373 
fluentd require rdkafka plugin
Related PR: https://github.com/kube-logging/fluentd-images/pull/142

feat: fluentd output plugin kafka support rdkafka2 client

---

pkg/resources/fluentd/appconfigmap.go

Fixes https://github.com/kube-logging/logging-operator/issues/814

fluentd-configcheck: disable inherited antiaffinity rules

---

charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
config/samples/containerd-log.yaml
controllers/logging/logging_controller.go
docs/configuration/crds/v1beta1/logging_types.md
pkg/resources/fluentbit/config.go
pkg/resources/fluentbit/configsecret.go
pkg/resources/fluentd/fluentd.go
pkg/sdk/logging/api/v1beta1/logging_types.go
pkg/sdk/logging/model/filter/concat.go
pkg/sdk/logging/model/filter/parser.go
pkg/sdk/logging/model/types/types.go
pkg/sdk/logging/plugins/plugin.go

Add support for the automatic configuration of docker compatible log parsing with the CRI log format. 
This has the following benefits:
- automatic json log parsing can happen using the Merge_Log Fluent Bit kubernetes filter
- downstream parsers can use the `log` field instead of `message` as they did with the docker runtime
- the `concat` and `parser` filters are automatically set back to use the `log` field instead of `message`
The example in the PR demonstrates a working configuration:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
name: containerd
spec:
enableDockerParserCompatibilityForCRI: true
```
After this, fluentbit can be configured through either the Logging or the FluentbitAgent resource. (Fluentbit configured through the `nodeAgents` field of the …

Log format compatibility

---

docs/configuration/crds/v1beta1/fluentbit_types.md
e2e/fluentd-aggregator-namespacelabel/fluentd_aggregator_test.go
pkg/sdk/logging/api/v1beta1/fluentbit_types.go

Enable kubernetes namespace labels added to the metadata by default

---

charts/logging-operator/README.md
charts/logging-operator/templates/logging/logging.yaml
charts/logging-operator/values.yaml

Add missing enableDockerParserCompatibilityForCRI flag to the helm chart to make it configurable

Add missing flag to chart

---

docs/configuration/plugins/outputs/logz.md
pkg/sdk/logging/model/output/logz.go
pkg/sdk/logging/model/output/logz_test.go
pkg/sdk/logging/model/output/zz_generated.deepcopy.go

Use pointer types to allow setting default true boolean fields to false
fixes #1723

Logzio boolean fields

---

charts/logging-operator/crds/logging.banzaicloud.io_fluentbitagents.yaml
charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
charts/logging-operator/crds/logging.banzaicloud.io_nodeagents.yaml
config/crd/bases/logging.banzaicloud.io_fluentbitagents.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_nodeagents.yaml
docs/configuration/crds/v1beta1/fluentbit_types.md
pkg/sdk/logging/api/v1beta1/fluentbit_types.go

Add missing option to control memory usage in persistent buffering mode.

fluentbit: storage.max_chunks_up

---

pkg/sdk/extensions/api/v1alpha1/systemdtailer.go

PR for issue https://github.com/kube-logging/logging-operator/issues/1809.
This changes the semantics of field `systemdFilter` to allow specifying a journal field. If none is specified, the behavior reverts to the default of assuming `_SYSTEMD_UNIT`.

Allow specifying alternate journal fields

---

.github/workflows/e2e.yaml

- This PR resolves an issue with conflicting uploads that occoured in #1807 by appending the kubeversion at the end of each test result upon uploading.

chore: resolve e2e test result conflict

---

.github/workflows/artifacts.yaml

Sets up image and chart signing.
Test run: https://github.com/kube-logging/logging-operator/actions/runs/11258053466
- Images and charts are signed with GitHub Actions OIDC token upon merging to main and releases, ensuring a seamless verification process for `Logging-operator` users.
- In case of both images and charts the digest is signed, which is a unique identifier of the artifacts. This ensures the integrity and authenticity of the artifacts.
`cosign verify "ghcr.io/kube-logging/logging-operator@{sha256-IMAGE-DIGEST}" \
--certificate-identity "https://github.com/ghcr.io/kube-logging/logging-operator/.github/workflows/artifacts.yaml@{refs/heads/main || refs/tags/<tag_name>}" \
--certificate-oidc-issuer "https://token.actions.githubusercontent.com"`
`cosign verify …

feat: add image and chart signing

---

charts/logging-operator/crds/logging.banzaicloud.io_fluentbitagents.yaml
charts/logging-operator/crds/logging.banzaicloud.io_fluentdconfigs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
charts/logging-operator/crds/logging.banzaicloud.io_syslogngconfigs.yaml
config/crd/bases/logging.banzaicloud.io_fluentbitagents.yaml
config/crd/bases/logging.banzaicloud.io_fluentdconfigs.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_syslogngconfigs.yaml
docs/configuration/crds/v1beta1/fluentbit_types.md
docs/configuration/crds/v1beta1/fluentd_types.md
docs/configuration/crds/v1beta1/syslogng_types.md
pkg/resources/fluentbit/daemonset.go
pkg/resources/fluentd/statefulset.go
pkg/resources/syslogng/statefulset.go
pkg/sdk/logging/api/v1beta1/fluentbit_types.go
pkg/sdk/logging/api/v1beta1/fluentd_types.go
pkg/sdk/logging/api/v1beta1/logging_types.go
pkg/sdk/logging/api/v1beta1/syslogng_types.go
pkg/sdk/logging/api/v1beta1/zz_generated.deepcopy.go

This PR enchances the buffer-metrics sidecar container by:
- Adding a new config option for setting a liveness probe.
- Increasing default resource values.

feat: enhance buffer-metrics sidecar

---

charts/logging-operator/crds/logging.banzaicloud.io_syslogngclusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_syslogngclusteroutputs.yaml
controllers/logging/logging_controller_test.go
docs/configuration/crds/v1beta1/logging_types.md
docs/configuration/crds/v1beta1/syslogng_clusteroutput_types.md
pkg/resources/model/reconciler.go
pkg/resources/model/system.go
pkg/sdk/logging/api/v1beta1/logging_types.go
pkg/sdk/logging/api/v1beta1/syslogng_clusteroutput_types.go
pkg/sdk/logging/model/syslogng/config/config.go
pkg/sdk/logging/model/syslogng/config/flow.go

- Adds protected flag for `SyslogNGClusterOutput` Kinds
- Fixes an issue with the protected flag on Fluentd, which created config-secret despite the flow was faulty
Fixes: #1731

feat: protected cluster output syslogng

---

pkg/resources/configcheck/configcheck.go
pkg/resources/fluentd/fluentd.go
pkg/resources/syslogng/syslogng.go

ConfigCheck cleaner was not aware of the logging resource and cleaned all configcheck secrets and pods that belonged to other logging resources. Adding the managed-by label to the cleaner filter solves this problem.

fix: configcheck cleaner label selector

---

.github/workflows/artifacts.yaml

Use AWS ECR mirror so CI won't fail with TOOMANYREQUESTS for the default one.
Signed-off-by: Szilard Parrag <szilard.parrag@axoflow.com>

chore(CI): Use AWS ECR location for trivy DBs

---

e2e/common/helpers.go
e2e/fluentd-aggregator-namespacelabel/fluentd_aggregator_test.go
e2e/fluentd-aggregator/fluentd_aggregator_test.go
e2e/volumedrain/volumedrain_test.go
pkg/sdk/logging/api/v1beta1/logging_types.go
pkg/sdk/logging/api/v1beta1/syslogng_types.go

- **chore: prepare for release with bumping fluentd image version**
- **chore: use moving image tag for axosyslog**

Prepare for release 4.11

---

pkg/resources/fluentbit/config.go
pkg/resources/fluentbit/daemonset.go

if logging-operator is deployed in IPv6 environment, fluentbit is not able to listen on http socket due the hard coded `HTTP_Listen` address. Make this dynamically set by `POD_IP` with an envVar definition

fix fluentbit ipv6 listen address

---

.github/workflows/artifacts.yaml

- If the `artifacts.yaml` workflow was pulled in from another repository if failed to sign the image due to invalid identity.
- Added `rekor-url` flag, so signing metadata will be publicly available, and can verify our artifacts upon deploying.

fix: image signing

---

.gitignore
pkg/resources/fluentbit/service.go
pkg/resources/fluentd/service.go
pkg/resources/nodeagent/service.go
pkg/resources/syslogng/service.go

- Use consts from `corev1` package, instead of string literals.
- Added devspace components to `.gitignore`.

 chore: use consts instead of literals

---

pkg/resources/fluentbit/prometheusrules.go
pkg/resources/fluentd/prometheusrules.go
pkg/resources/syslogng/prometheusrules.go
pkg/sdk/logging/api/v1beta1/common_types.go
pkg/sdk/logging/api/v1beta1/commont_types_test.go

- The Prometheus-rule override functionality was faulty, because the original implementation had a sequential override problem where each subsequent override would replace the previous one completely, rather than applying multiple overrides cumulatively.
- The conditional check inside the `Override()` method doesn't actually prevent the method from returning a rule - it just conditionally modifies the rule.
- These issues combined would lead to creating duplicate or unnecessary modified versions of all rules, while swapping the whole list every iteration, rather than selectively overriding only the rules that match specific criteria.
Fixes: #1842

fix: prometheus rule overrides swaps whole list

---

.github/archive/trigger-submodule-update.yaml
.github/workflows/artifacts.yaml
.github/workflows/ci.yaml
.github/workflows/e2e.yaml

Fixes: #1864 and also updates all other workflow deps.

chore(deps): bump deps

---

charts/logging-operator/charts/logging-operator-crds/templates/logging-extensions.banzaicloud.io_hosttailers.yaml
charts/logging-operator/crds/logging-extensions.banzaicloud.io_hosttailers.yaml
config/crd/bases/logging-extensions.banzaicloud.io_hosttailers.yaml
pkg/sdk/extensions/api/v1alpha1/eventtailer_types.go
pkg/sdk/extensions/api/v1alpha1/hosttailer_types.go

Fixes: #1834 
NOTE: This will not break this piece of code: <https://github.com/kube-logging/logging-operator/blob/e45bb86c02c76b132083d3d799bf9fa5abbc4988/pkg/resources/hosttailer/hosttailer.go#L168-L170> since `Merge()` starts with a nil check.

fix: make workload meta overrides not required

---

Dockerfile

This PR fixes the following warning:

chore: lint dockerfile

---

Makefile
charts/logging-operator/README.md
charts/logging-operator/templates/clusterrole.yaml
charts/logging-operator/templates/clusterrolebinding.yaml
charts/logging-operator/templates/serviceaccount.yaml
charts/logging-operator/values.yaml
controllers/logging/logging_controller.go
main.go

This PR aims to address the issue raised in #1859.
The issue arises because Helm does not guarantee a precise order in which it deletes resources. Although this order can be influenced via hooks and weights, there are limitations. For example, hooks may not work as expected in ArgoCD environments.
- Added a new flag to the operator service: `finalizer-cleanup`. This flag should be used in conjunction with `.Values.rbac.retainOnDelete`.
- When both options are set and `helm uninstall` is executed:
1. Helm will retain the operator's service account as well as its cluster role and cluster role binding. This is necessary because Helm uninstalls resources in an unpredictable order.
2. The operator will attempt to free up its managed logging resources by removing finalizers, which would …

feat: add option to cleanup stuck finalizers

---

charts/logging-operator/crds/logging.banzaicloud.io_fluentbitagents.yaml
charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_fluentbitagents.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
config/samples/multitenant-routing/logging/tenant-infra-logging.yaml
docs/configuration/crds/v1beta1/fluentbit_types.md
pkg/resources/fluentbit/config.go
pkg/resources/fluentbit/configsecret.go
pkg/sdk/logging/api/v1beta1/fluentbit_types.go

HotReload pauses all inputs and waits until they finish. 
In certain situations this is unacceptable, for example if an output is down for a longer time. 
An undocumented option called "Hot_Reload.Ensure_Thread_Safety Off" can be used at the [SERVICE] config to force hotreload after the grace period. 
Please note that it might result in a SIGSEGV, but worst case kubelet will restart the container. 
See https://github.com/fluent/fluent-bit/pull/7509
Example config:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
spec:
forceHotReloadAfterGrace: true
```

feat: force HotReload after grace period instead of blocking indefinitely

---

pkg/resources/fluentbit/config.go
pkg/resources/fluentbit/configsecret.go
pkg/resources/fluentd/config.go
pkg/resources/fluentd/configsecret.go

Fixes: #1870
Relates: #1890
- IPv6 was not wired in properly, so it had no effect.
- Once it was wired in it turned out to be faulty:
```sh
[error]: unexpected error error_class=SocketError error=#<SocketError: getaddrinfo: Name or service not known>
```

fix: fluentd prom metrics invalid addr

---

pkg/resources/fluentd/config.go

This reverts commit 386eaf0f3364caab3192c92e46882fca8c71ee97.
Fixes the issue reported in #1890 
IPv6 is available in version 5.0 of the logging operator

Revert "expose fluentd metrics also on IPv6"

---

charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_clusteroutputs.yaml
charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_outputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_outputs.yaml
docs/configuration/plugins/outputs/http.md
pkg/sdk/logging/model/output/http.go
pkg/sdk/logging/model/output/http_test.go
pkg/sdk/logging/model/output/zz_generated.deepcopy.go

fluentd > 1.7 introduced new functionality and parameters that can help many organisations 
https://docs.fluentd.org/output/http
This pull request includes several changes to the `logging-operator` CRD templates and base configurations. The changes mainly involve the addition of new properties to the specifications of `clusteroutputs` and `outputs` resources.
* Added `compress` property of type `string` to `clusteroutputs` and `outputs` specifications in multiple files. [[1]](diffhunk://#diff-572c405153f17c52d00943eee31bf16f1c963e3ebc1084bdb6cb5c28892acdedR2858-R2859) [[2]](diffhunk://#diff-04e78bda53bdcf3dd4dfd3bdab56a659388b30d9a08e1afa1f17f77cfbe91a91R2854-R2855) [[3]](diffhunk://#diff-ca883a53d29fb10eeec83ac9b04b7d725d2ff32e24305a1e405904a25253671eR2855-R2856) …

feat(http): add support for new available parameters 

---

charts/logging-operator/templates/clusterrole.yaml
config/rbac/role.yaml
controllers/logging/logging_controller.go

Example configuration needed to run on Openshift:
```
fluentbit:
security:
createOpenShiftSCC: true
roleBasedAccessControlCreate: true
securityContext:
privileged: true
runAsUser: 0
```

fix: add missing roles to grant the use of scc to workloads

---

charts/logging-operator/README.md
charts/logging-operator/templates/logging/hosttailer.yaml
charts/logging-operator/templates/logging/hosttailers.yaml
charts/logging-operator/values.yaml

Fixes: https://github.com/kube-logging/logging-operator/issues/1909
`logging.hostTailer` is superseded by `logging.hostTailers` and will be removed in a future release
```yaml
logging:
enabled: true
hostTailers:
enabled: true
instances:
- name: kubeauditane
enabled: true
workloadOverrides:
nodeSelector:
node-role.kubernetes.io/control-plane: "true"
tolerations:
- key: node-role.kubernetes.io/control-plane
operator: Exists
effect: NoSchedule
fileTailers:
- name: kube-audit
path: /var/lib/rancher/rke2/server/logs/*.log
- name: workersnodesonly
enabled: true
workloadOverrides:
nodeSelector:
node-role.kubernetes.io/worker: "true"
fileTailers:
- name: kube-audit
path: /var/lib/rancher/rke2/agent/logs/*.log
```

feat(chart): enable defining multiple hosttailers

---

charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
docs/configuration/crds/v1beta1/logging_types.md
pkg/resources/model/reconciler.go
pkg/resources/model/repository.go
pkg/sdk/logging/api/v1beta1/logging_types.go

Fixes: https://github.com/kube-logging/logging-operator/issues/1140
Fixes: https://github.com/kube-logging/logging-operator/issues/700

fix(validation-reconciler): correct output and flow status report

---

controllers/logging/logging_controller_test.go
e2e/common/setup/loggingoperator.go
e2e/logging_metrics_monitoring/logging_metrics_monitoring_test.go
e2e/watch-selector/watch_selector_test.go
main.go
pkg/resources/fluentbit/configsecret.go
pkg/resources/fluentd/appconfigmap.go
pkg/resources/fluentd/configsecret.go
pkg/resources/fluentd/outputsecret.go
pkg/resources/syslogng/configcheck.go
pkg/resources/syslogng/configsecret.go
pkg/resources/syslogng/outputsecret.go

The point is to introduce a backwards compatible option to reduce memory usage in large environments.
The PR introduces two new operator flags:
- `watch-labeled-children`: only watch child resources (pods, daemonsets, configmaps, etc) created by the operator with specific labels to avoid watching resources the operator is not concerned with. This option will be enabled by default in a future new **minor** version.
- `watch-labeled-secrets`: only watch secrets with `logging.banzaicloud.io/watch: enabled` label. This has the risk of breaking the operator if certain secrets are not labeled correctly. This option will be enabled by default in a future new **major** version.
Fixes: #1930 in https://github.com/kube-logging/logging-operator/pull/1929/commits/5f5aee023fc1890b5a6b782c061cff39c31b57 …

Fine tune watch selectors for less memory usage

---

.github/workflows/ci.yaml
.github/workflows/e2e.yaml
Makefile

This is a proper fix instead of the workaround introduced in ae06c5711abbf49a24a5abdfcc5b0d67b06472a0

chore(ci): update go-test-coverage to utilize source-dir parameter

---

Makefile

The CI could fail if the e2e tests were cached, since no coverage files would be created.
eg.: https://github.com/kube-logging/logging-operator/actions/runs/14020628629/job/39252238195?pr=1988

fix(ci-e2e): make sure e2e tests are not cached

---

charts/logging-operator/README.md
charts/logging-operator/templates/userrole.yaml
charts/logging-operator/values.yaml

- Introduce `rbac.createAggregatedEditClusterRole` and `rbac.createAggregatedAdminClusterRole` to control the deployment of existing `edit` and `admin` aggregated cluster roles. Defaults to `true` to retain current behavior.
- Introduce `rbac.createAggregatedViewClusterRole` to control the deployment of a new `view` aggregated cluster role. Defaults to `false` to retain current behavior.

feat(chart): aggregated view clusterrole

---

pkg/sdk/logging/api/v1beta1/fluentd_types.go

feat: set default user and group

---

charts/logging-operator/README.md
charts/logging-operator/values.yaml

fix(chart): nodeagent deprecation notice

---

pkg/resources/fluentbit/config.go
pkg/resources/fluentbit/configsecret.go

`Parsers_File` with the path to the `cri-log-compatibility` parser configuration should be added if the `enableDockerParserCompatibilityForCRI` option is used in the `Logging` resource.
This PR fixes: #2025

fix: add Parsers_File to fluent-bit.conf if enableDockerParserCompatibilityForCRI is enabled

---

charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngclusteroutputs.yaml
charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngoutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_syslogngclusteroutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_syslogngoutputs.yaml
config/crd/bases/logging.banzaicloud.io_syslogngclusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_syslogngoutputs.yaml
docs/configuration/plugins/syslogng-outputs/disk_buffer.md
docs/configuration/plugins/syslogng/outputs/disk_buffer.md
docs/syslogng-quickstart.md
pkg/sdk/logging/model/syslogng/config/output_tests/loki_test.go
pkg/sdk/logging/model/syslogng/output/disk_buffer.go

Issue #2021 provides a detailed description of the problem with generating the Axosyslog configuration file when using the `q_out_size` attribute in `disk_buffer` parameter in `SyslogNGClusterOutput`/`SyslogNGOutput`.
After fixing the configuration file format (rename `q_out_size` to `qout_size`), the `configcheck` pod no longer shows a warning when validating the Axosyslog configuration
```
...
@version: current
@include "scl.conf"
source "main_input" {
channel {
source {
network(flags("no-parse") port(601) transport("tcp") max-connections(100) log-iw-size(10000));
};
parser {
json-parser(prefix("json."));
};
};
};
destination "clusteroutput_cattle-logging-system_loki-cluster-output" {
loki(auth(insecure()) labels(
"cluster" => "internal"
"type" => "vault-audit-log"
) …
```

fix: change q_out_size attribute in disk_buffer parameter to qout_size in SyslogNGClusterOutput/SyslogNGOutput

---

pkg/sdk/logging/model/output/kafka.go
pkg/sdk/logging/model/output/kafka_test.go

Issue #2017 provides a detailed description of the problem with generating the Fluentd configuration file when using the `rdkafka_options` parameter in `ClusterOutput`/`Output`.
After fixing the configuration file format, the `logging-operator-fluentd-configcheck` pod no longer shows a warning when validating the Fluentd configuration
```
...
<match **>
@type copy
<store>
@type "rdkafka2"
@id clusterflow:logging-system:opensearch:clusteroutput:logging-system:opensearch
brokers "broker:9092"
default_topic "default"
topic_key "$.kubernetes.namespace_name"
rdkafka_options {"sasl.mechanisms":"PLAIN","sasl.username":"user","security.protocol":"SASL_SSL","ssl.ca.location":"/etc/ssl/certs/ca-certificates.crt","ssl.certificate.location":"/etc/ssl/certs/tls.crt","ssl.key.location":"/etc/ssl/certs/t …
```

fix: change rdkafka_options format from section to hash

---

charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngclusteroutputs.yaml
charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngoutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_syslogngclusteroutputs.yaml
charts/logging-operator/crds/logging.banzaicloud.io_syslogngoutputs.yaml
config/crd/bases/logging.banzaicloud.io_syslogngclusteroutputs.yaml
config/crd/bases/logging.banzaicloud.io_syslogngoutputs.yaml
docs/configuration/plugins/syslogng-outputs/loki.md
pkg/sdk/logging/model/syslogng/config/output_tests/loki_test.go
pkg/sdk/logging/model/syslogng/output/loki.go

The Loki destination plugin in AxoSyslog allows setting the tenant value for the events being sent via the [tenant-id()](https://axoflow.com/docs/axosyslog-core/chapter-destinations/destination-loki/#tenant-id) option.
Adding this parameter to `SyslogNGClusterOutput`/`SyslogNGOutput` will allow sending events to different tenants in a multi-tenant Loki environment.
Without specifying this option, it is not possible to use AxoSyslog Loki output in a multi-tenant Loki environment with authentication enabled.
An error will be displayed in the pod with the AxoSyslog aggregator:
```
Error sending Loki batch; error='no org id', details='', location='/etc/syslog-ng/config/syslog-ng.conf:17:5'
```

Add support for Loki tenant-id to SyslogNGClusterOutput/SyslogNGOutput

---

charts/logging-operator/charts/logging-operator-crds/templates/logging-extensions.banzaicloud.io_hosttailers.yaml
charts/logging-operator/crds/logging-extensions.banzaicloud.io_hosttailers.yaml
config/crd/bases/logging-extensions.banzaicloud.io_hosttailers.yaml
docs/configuration/crds/extensions/v1alpha1/hosttailer_types.md
pkg/sdk/extensions/api/v1alpha1/filetailer.go
pkg/sdk/extensions/api/v1alpha1/hosttailer_types.go
pkg/sdk/extensions/api/v1alpha1/systemdtailer.go

Closes https://github.com/orgs/kube-logging/discussions/1916

feat(hosttailer): reduce fluent-bit log level to error

---

charts/logging-operator/README.md
charts/logging-operator/values.yaml

The default value of `priorityClassName` is currently a map/object, but is used as a string when setting it on the deployment.
This change sets the default value to null (using `~`), and is now considered a string value.
Fixes #2031

fix(helm): priorityClassName must be of type string

---

docs/configuration/plugins/outputs/loki.md
pkg/sdk/logging/model/output/loki.go

Fix incorrect doc for default LineFormat for loki logs.
https://kube-logging.dev/docs/configuration/plugins/outputs/loki/

Fix incorrect doc for default LineFormat for loki

---

pkg/resources/fluentbit/daemonset.go

We missed a thing in https://github.com/kube-logging/logging-operator/pull/2043
This PR ensures that volume and volumeMount is set only if switch "disableVarLog" is set to true

bugfix: mount /var/log only if config parameter is set to false

---

e2e/common/cond/conditions.go
e2e/fluentd-aggregator/fluentd_aggregator_test.go
pkg/resources/fluentd/appconfigmap.go

Fixes #2083. Also adjusts the tests to actually retrieve the updated status of the `Logging` object and wait for any ConfigCheck to run to completion.

Make /tmp directory for configchecks sticky so StartWithTimeout strategy

---

controllers/logging/tenant_test.go

This lonely test-case was a flaky since the last release, the cause is still unknown from the [logs](https://github.com/kube-logging/logging-operator/actions/runs/17465736163/job/49603384915) it looks like some weird eventually consistency is happening...

fix: flaky find tenants test

---

images/fluentd/Dockerfile

Snappy is a common `compression_codec` for Kafka Logging Output. Unfortunatelly the plugin is missing in the fluentd 1´.18 Dockerfile, it was previously installed in [1.16](https://github.com/kube-logging/fluentd-images/blob/main/v1.16-4.10/Dockerfile#L42), maybe the use case is not broad that the gem module was missing so far.

add snappy gem for fluentd

---

charts/logging-operator/README.md
charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
charts/logging-operator/templates/logging/logging.yaml
charts/logging-operator/values.yaml
config/crd/bases/logging.banzaicloud.io_loggings.yaml
docs/configuration/crds/v1beta1/logging_types.md
e2e/fluentbit-agent-namespace/fluentbit_agent_namespace_test.go
e2e/fluentbit-nodeagents-namespace/fluentbit_nodeagents_namespace_test.go
pkg/resources/fluentbit/configsecret.go
pkg/resources/fluentbit/meta.go
pkg/resources/fluentbit/rbac.go
pkg/resources/fluentbit/service.go
pkg/sdk/logging/api/v1beta1/logging_types.go

Summary
- Introduces Logging.spec.fluentBitAgentNamespace (immutable) to place Fluent Bit resources in a separate namespace from the control plane. Fixes [2104](https://github.com/kube-logging/logging-operator/issues/2104)
- Defaults to spec.controlNamespace for backwards compatibility.
Motivation
- Separate privileged node agents from restricted control plane to comply with PSA and organizational segregation.
- Clearer ownership and RBAC boundaries for platform vs. infra teams.
What’s changed
- API: LoggingSpec gains fluentBitAgentNamespace; defaulting is applied in SetDefaults()
- FluentBit reconcilers:
- ObjectMeta.Namespace now uses logging.Spec.fluentBitAgentNamespace
- RBAC subjects reference ServiceAccount in fluentBitAgentNamespace
- CRDs and Helm chart CRDs/docs regenerated
- …

Add spec.fluentBitAgentNamespace to run Fluent Bit in a dedicated namespace

---

.github/workflows/e2e.yaml
Makefile
e2e/common/kind/commands.go

The e2e tests in the pipeline were failing due to the following error:
```sh
Output: Image: "fluentd-full:local" with ID "sha256:be9da3947b19a27052908c44a187be6cadcae109007bc3741e98e491d76a38cb" not yet present on node "fluentbit-hotreload-control-plane", loading...
ERROR: failed to load image: command "docker exec --privileged -i fluentbit-hotreload-control-plane ctr --namespace=k8s.io images import --all-platforms --digests --snapshotter=overlayfs -" failed with error: exit status 1
Command Output: unpacking docker.io/library/fluentd-full:local (sha256:35c46a45dd6da8e7ed1f7ffeff10670f17c6958ffb64145d581c39414f6ec8a1)...time="2025-10-01T13:48:41Z" level=info msg="apply failure, attempting cleanup" error="failed to extract layer sha256:57892029ff7cdba00a5574383a125683542a563b89ad69ffd082f5 …
```

fix: e2e tests
